'use strict';
(() => {
const app=document.getElementById('app'), frame=document.getElementById('frame');
const icons={home:'M3 10 12 3l9 7M5 9v11h5v-6h4v6h5V9',calendar:'M5 4h14a2 2 0 0 1 2 2v14H3V6a2 2 0 0 1 2-2M7 2v4m10-4v4M3 10h18',trophy:'M8 3h8v6a4 4 0 0 1-8 0V3M8 5H4v3a4 4 0 0 0 4 4m8-7h4v3a4 4 0 0 1-4 4m-4 1v6m-4 2h8',pin:'M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0M15 10a3 3 0 1 1-6 0 3 3 0 0 1 6 0',user:'M16 6a4 4 0 1 1-8 0 4 4 0 0 1 8 0M4 21v-2a8 8 0 0 1 16 0v2',bell:'M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4',settings:'M12 8a4 4 0 1 1 0 8 4 4 0 0 1 0-8M12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2',search:'M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0m-2 5 6 6',chevron:'m9 5 7 7-7 7',back:'m15 5-7 7 7 7',down:'m6 9 6 6 6-6',close:'m6 6 12 12M6 18 18 6',check:'m4 12 5 5L20 6',clock:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0M12 6v6l4 2',chart:'M3 3v18h18M7 16l5-6 4 3 5-8',history:'M3 11a9 9 0 1 1 3 8M3 4v7h7m2-5v6l4 2',shield:'M12 2 3 6v6c0 6 9 10 9 10s9-4 9-10V6l-9-4',help:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0M9 8a3 3 0 1 1 4 4v2m-1 3h.01',network:'M10 2h4v4h-4V2M3 17h4v4H3v-4m14 0h4v4h-4v-4M5 17v-5h14v5m-7-5V6',logout:'M9 4H3v16h6m5-4 4-4-4-4m-6 4h13',mail:'M3 5h18v14H3V5m0 0 9 7 9-7',phone:'M6 3h4l1 5-3 2c2 3 3 4 6 6l2-3 5 1v4c0 5-6 3-11-1S1 3 6 3',upload:'M12 16V3m-5 5 5-5 5 5M3 16v5h18v-5',play:'m8 4 13 8-13 8V4',card:'M3 5h18v14H3V5m0 5h18m-14 5h3',star:'m12 2 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1 3-6',empty:'M3 9h18v11H3V9m0 0 4-5h10l4 5M9 14h6',alert:'m12 3 10 18H2L12 3m0 5v6m0 3h.01'};
const ic=(name)=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${icons[name]||icons.chevron}"/></svg>`;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const urls={home:'/home',tournaments:'/tournaments',clubs:'/clubs',rating:'/rating',profile:'/profile',history:'/profile/tournaments',achievements:'/achievements',statistics:'/statistics',settings:'/settings',broadcast:'/settings',about:'/srp',leagues:'/leagues',privacy:'/privacy',consent:'/personal-data-consent',updates:'/updates',login:'/auth/login',reset:'/auth/reset-password'};
const screens=[
['home','Главная','Основные разделы','verified'],['tournaments','Лобби турниров','Основные разделы','verified'],['tournament','Предстоящий турнир','Турниры','verified'],['completed','Завершённый турнир','Турниры','verified'],['history','История турниров','Турниры','verified'],
['leagues','Лиги SRP','Лиги','verified'],['city-event','Лига Городов: событие','Лиги','verified'],['champion-event','Лига Чемпионов: этап','Лиги','inferred'],['rating-event','Лига Рейтинга: финал клуба','Лиги','verified'],['ambassadors','Лига Амбассадоров · скоро','Лиги','verified'],
['clubs','Каталог клубов','Клубы и рейтинг','unavailable'],['club','Карточка клуба','Клубы и рейтинг','inferred'],['map','Карта клубов','Клубы и рейтинг','unavailable'],['rating','Рейтинг игроков','Клубы и рейтинг','verified'],['player','Профиль игрока','Клубы и рейтинг','verified'],['player-history','Турниры другого игрока','Клубы и рейтинг','verified'],['player-achievements','Достижения другого игрока','Клубы и рейтинг','verified'],['player-statistics','Статистика другого игрока','Клубы и рейтинг','verified'],
['profile','Мой аккаунт','Аккаунт','verified'],['achievements','Достижения и прогресс','Аккаунт','verified'],['statistics','Статистика игрока','Аккаунт','verified'],['settings','Настройки профиля','Аккаунт','verified'],['broadcast','Профиль для трансляции','Аккаунт','verified'],['notifications','Центр уведомлений','Аккаунт','verified'],['push-settings','Настройки уведомлений','Аккаунт','new'],['loyalty','Карта лояльности · скоро','Аккаунт','verified'],
['welcome','Стартовый экран','Авторизация','verified'],['login','Вход','Авторизация','verified'],['register','Регистрация','Авторизация','inferred'],['reset','Восстановление пароля','Авторизация','inferred'],['verify','Подтверждение контакта','Авторизация','inferred'],
['about','О сети и правила','Справка','verified'],['support','Поддержка','Справка','inferred'],['updates','Обновления приложения','Справка','inferred'],['install','Установить приложение','Справка','verified'],['privacy','Политика конфиденциальности','Справка','verified'],['consent','Обработка персональных данных','Справка','verified']
].map(([id,title,group,status])=>({id,title,group,status}));
const events=[
{id:0,name:'Сателлит на ЛГ',date:'07.10',time:'18:00',cap:100,type:'Сателлит',game:'NLH'},
{id:1,name:'Холдем / Ананас',date:'07.10',time:'18:00',cap:100,type:'Клубный',game:'NLH'},
{id:2,name:'Лига Чемпионов',date:'07.10',time:'19:00',cap:7,type:'Лига',game:'NLH'},
{id:3,name:'Сателлит на ЛГ',date:'08.10',time:'18:00',cap:100,type:'Сателлит',game:'NLH'},
{id:4,name:'MYSTERY BOUNTY',date:'08.10',time:'18:00',cap:100,type:'Клубный',game:'NLH'},
{id:5,name:'Crazy феникс',date:'09.10',time:'18:00',cap:100,type:'Клубный',game:'NLH'},
{id:6,name:'Лига Городов · 1A',date:'10.10',time:'16:00',cap:145,type:'Лига',game:'NLH',route:'city-event'},
{id:7,name:'Лига Городов · Final',date:'11.10',time:'14:00',cap:145,type:'Лига',game:'NLH',route:'city-event'},
{id:8,name:'Феникс',date:'10.10',time:'17:00',cap:100,type:'Клубный',game:'NLH'},
{id:9,name:'Кубковый турнир',date:'11.10',time:'15:00',cap:100,type:'Клубный',game:'NLH'}];
const past=[['Баунти ПКО','06.10',27],['Классический','05.10',80],['Феникс','03.10',57],['MYSTERY BOUNTY','01.10',64],['Кубковый турнир','27.09',34],['Crazy феникс','25.09',94],['MYSTERY BOUNTY','24.09',36],['Холдем / Ананас','23.09',53],['Феникс','19.09',10],['Crazy феникс','18.09',8],['Баунти ПКО','15.09',39],['Классический','14.09',10]];
const publicPast=[['Баунти ПКО','06.10',7],['Классический','05.10',8],['Кубковый турнир','04.10',16],['Сателлит на ЛГ','04.10',6],['Феникс','03.10',1],['Crazy феникс','02.10',3],['MYSTERY BOUNTY','01.10',42],['Холдем / Ананас','30.09',6],['Баунти ПКО','29.09',57],['Классический','28.09',68]];
const players=[['Амир Нуриев',1501],['Амрах Иманов',1378],['Амир Галиаскаров',1366],['sinester222',1349],['Евгений Трифанов',1323],['Олег Дегтярев',1293],['Ибрагимов Реналь',1248],['Рустем Закиров',1242],['Другой Олег',1240],['Хмурый',1233],['Никита Лазарев',1227],['Сулейманов Айдар',1221],['CrazyPirate4738',1209],['Сафин Тагир',1203],['Владислав Тамбов',1186],['SneakyPigeon6471',1172],['Палеев Дмитрий',1172],['Кыргый',1170],['Сергей Пушкин',1169],['Альберт Галимов',1151]];
const clubData=[['Milli Club','Казань'],['Легион','Ижевск'],['Марьяж','Йошкар-Ола'],['СРП','Нижний Новгород'],['СРП','Альметьевск'],['СРП','Набережные Челны'],['СРП Ривер','Челябинск'],['СРП_Е (Оптимист)','Екатеринбург'],['СРПЕ (Шеф)','Екатеринбург'],['Улей','Уфа'],['Фан Покер','Ярославль'],['Феникс','Липецк'],['Феникс','Энгельс'],['Феникс','Воронеж'],['Ace-King','Чебоксары'],['Aria Royale','Москва'],['Aztec Club','Киров'],['BD bar','Новочеркасск'],['Big Blind','Обнинск'],['KINGSMAN','Рязань'],['Moscow Students Poker River Room','Москва'],['Raise Club','Санкт-Петербург'],['River Room','Нижнекамск'],['River Room','Москва'],['River Room','Оренбург'],['River Room','Брянск'],['River Room','Тюмень'],['River Room','Омск']];
const questions=['Ваши фамилия и имя','Из какого вы города и как называется ваш клуб?','Работаете ли над игрой? Если да, то как?','Чем вы занимаетесь и чем вы увлекаетесь вне покера?','Как давно вы играете в покер и как познакомились с СРП?','Каким своим достижением в СРП вы гордитесь больше всего?','Какое место покер занимает в вашей жизни сейчас?','Какую покерную цель вы ставите перед собой на ближайший год?','Какой совет вы дали бы себе в начале покерного пути?','Чему покер вас научил?','Кто за вас сегодня болеет и кому хотите передать привет?'];
const blinds=[[500,1000,0,30],[500,1000,1000,30],[1000,2000,2000,30],[1500,3000,3000,30],[2000,4000,4000,20],[3000,6000,6000,20],[4000,8000,8000,20],[5000,10000,10000,20],[6000,12000,12000,20],[8000,16000,16000,20],[10000,20000,20000,15],[15000,30000,30000,15],[20000,40000,40000,15],[25000,50000,50000,15],[30000,60000,60000,10],[40000,80000,80000,10],[50000,100000,100000,10],[75000,150000,150000,10],[100000,200000,200000,10],[150000,300000,300000,10],[200000,400000,400000,10],[250000,500000,500000,10],[300000,600000,600000,10],[400000,800000,800000,7],[500000,1000000,100000,7]];
const ordinary=[{name:'Первая победа',desc:'Занять 1-е место в любом турнире',now:1,max:1,group:'Победы и места'},{name:'Топ-9',desc:'Впервые попасть на финальный стол',now:1,max:1,group:'Победы и места'},{name:'Серия побед',desc:'3 победы подряд в одном сезоне',now:1,max:3,group:'Победы и места'},{name:'Первая игра',desc:'Сыграть первый турнир',now:1,max:1,group:'Активность'},{name:'Мультиплощадка',desc:'Сыграть в 3+ клубах сети',now:1,max:3,group:'Активность'},{name:'Командный турнир',desc:'Принять участие в командном типе турнира',now:0,max:1,group:'Активность'},{name:'Командный турнир',desc:'Победить в командном турнире',now:0,max:1,group:'Активность'}];
const rare=[...['Баунти хантер','Истинный регуляр','Олигарх'].flatMap((group,g)=>[20,50,100,250,500,1000].map((n,i)=>({name:g===0?`Заработать ${n} баунти`:g===1?`Посетить ${[10,25,100,300,500,1000][i]} игр`:`Сделать ${[10,25,50,100,300,500][i]} реентри`,desc:'Описание достижения скоро появится',now:[10,79,130][g],max:g===0?n:g===1?[10,25,100,300,500,1000][i]:[10,25,50,100,300,500][i],group,level:i+1})) )];
const defaults={nick:'Ваграм Карапетян',club:0,registered:[],tripPlan:[],push:{reminder:true,event:true,result:true,promo:false},broadcast:{},readNotifications:false};
let saved={};try{saved=JSON.parse(localStorage.getItem('srp-prototype-v2')||'{}');}catch{}
const state={...defaults,...saved,page:'home',selected:0,detailTab:'О турнире',league:'Городов',leagueTab:'О турнире',ratingTab:'Мой клуб',achTab:'Обычные',historyTab:'Мои',clubsTab:'Все',clubCity:'Все города',filter:'Все',search:'',dateFilter:'Все даты',historyLimit:6,player:0,pastIndex:0,viewState:'normal',device:'desktop',returnPage:'home',authError:'',modal:null,mapClub:0,round:4};
state.push={...defaults.push,...saved.push};state.registered=Array.isArray(saved.registered)?saved.registered:[];
function save(){try{localStorage.setItem('srp-prototype-v2',JSON.stringify({nick:state.nick,club:state.club,registered:state.registered,tripPlan:state.tripPlan,push:state.push,broadcast:state.broadcast,readNotifications:state.readNotifications}));}catch{}}
const num=n=>Number(n).toLocaleString('ru-RU');

const mediaBase='media/';
function srpVideo(name,poster,extra=''){return `<img class="srp-video-poster" src="${mediaBase}${poster}" alt=""><video class="srp-video" src="${mediaBase}${name}" poster="${mediaBase}${poster}" autoplay muted loop playsinline preload="metadata" aria-label="Оригинальное видео SRP" ${extra}></video>`;}
function mediaBanner(){const second=state.mediaSlide===1;return `<section class="video-banner">${srpVideo(second?'home-film-3.mp4':'home-film-2.mp4',second?'home-film-3-poster.jpg':'home-film-2-poster.jpg')}<div class="video-shade"></div><div class="video-banner-copy"><div class="eyebrow">ФЕДЕРАЛЬНАЯ СЕТЬ</div><img class="hero-wordmark" src="${mediaBase}srp-wordmark.svg" alt="СРП"><h2>Твоя игра. Твой клуб.</h2><p>Турниры и лиги по всей России</p>${link('tournaments','К турнирам','primary')}</div><div class="media-switch" aria-label="Видео главной">${[0,1].map(i=>`<button data-action="media-slide" data-value="${i}" aria-label="Видео ${i+1}" aria-pressed="${(state.mediaSlide||0)===i}">${i+1}</button>`).join('')}</div></section>`;}
function leagueMedia(route,title,copy,name,poster){return `<a href="#${route}" data-route="${route}" class="league-media">${srpVideo(name,poster)}<div class="video-shade"></div><div class="league-media-copy"><h3>${title}</h3><p>${copy}</p></div></a>`;}
function rail(){return `<aside class="account-rail" aria-label="Быстрый доступ">${link('profile',avatar(),'rail-avatar')}<strong>${esc(state.nick)}</strong><small>${esc(clubData[state.club][0])}</small>${link('tournaments','Турниры','rail-entry')}${link('rating',ic('trophy')+'Рейтинг','rail-entry')}${link('achievements',ic('star')+'Достижения','rail-entry')}${link('loyalty',ic('card')+'Лояльность','rail-entry')}${link('notifications',ic('bell')+'Уведомления','rail-entry')}${link('settings',ic('settings')+'Настройки','rail-entry')}</aside>`;}

const pill=(t,c='')=>`<span class="pill ${c}">${t}</span>`;
const btn=(t,a,c='secondary',more='')=>`<button class="${c}" data-action="${a}" ${more}>${t}</button>`;
const link=(page,t,c='',more='')=>`<a href="#${page}" data-route="${page}" class="${c}" ${more}>${t}</a>`;
const initials=n=>n.split(' ').filter(Boolean).map(p=>p[0]).slice(0,2).join('').toUpperCase();
function avatar(n=state.nick,large=false){return `<span class="avatar ${large?'large':''}">${state.avatar&&n===state.nick?`<img alt="Фото профиля" src="${state.avatar}">`:esc(initials(n))}</span>`;}
function pageHead(t,sub='',actions=''){return `<div class="page-head"><div><div class="eyebrow">${sub||'Milli Club · Казань'}</div><h1>${t}</h1></div><div class="head-actions">${actions}</div></div>`;}
function back(to='home',t='Назад'){return link(to,ic('back')+t,'back');}
function tabs(items,value,action){return `<div class="tabs" role="group" aria-label="Разделы">${items.map(t=>`<button class="${value===t?'active':''}" data-action="${action}" data-value="${t}" aria-pressed="${value===t}">${t}</button>`).join('')}</div>`;}
function tabline(items,value,action){return `<div class="tabline" role="group" aria-label="Вкладки">${items.map(t=>`<button class="${value===t?'active':''}" data-action="${action}" data-value="${t}" aria-pressed="${value===t}">${t}</button>`).join('')}</div>`;}
function field(label,name,type='text',value='',extra=''){return `<label class="field">${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;}
function searchBox(ph,kind='events'){return `<label class="search">${ic('search')}<input type="search" data-search="${kind}" aria-label="${ph}" placeholder="${ph}" value="${esc(state.search)}"></label>`;}
function empty(t,p='',action='',compact=false){return `<div class="empty ${compact?'compact':''}"><div class="empty-icon">${ic('empty')}</div><h3>${t}</h3><p>${p}</p>${action}</div>`;}
function accountNav(active){return `<nav class="account-subnav" aria-label="Разделы аккаунта">${[['profile','Аккаунт'],['history','История'],['achievements','Достижения'],['statistics','Статистика'],['settings','Настройки']].map(([id,t])=>link(id,t,id===active?'active':'')).join('')}</nav>`;}
function clubSelect(action='league-club'){return `<select aria-label="Выбор клуба" data-select="${action}">${clubData.map((c,i)=>`<option value="${i}" ${i===state.club?'selected':''}>${esc(c[0])} · ${esc(c[1])}</option>`).join('')}</select>`;}
function visibleEvents(){return events.filter(e=>(state.filter==='Все'||(state.filter==='Мои'?state.registered.includes(e.id):e.type===state.filter))&&(state.dateFilter==='Все даты'||e.date===state.dateFilter)&&e.name.toLowerCase().includes(state.search.toLowerCase()));}
function eventRows(items=visibleEvents()){return `<div class="panel lobby-list"><div class="list-labels"><span>Начало</span><span>Турнир</span><span>Игроки</span><span>Статус</span></div>${items.map(e=>`<button class="event-row ${state.selected===e.id?'selected':''}" data-action="select-event" data-value="${e.id}" aria-pressed="${state.selected===e.id}"><span class="time">${e.time}<small class="date">${e.date}.2026</small></span><span><span class="event-name">${e.name}</span><span class="event-meta">Холдем · ${e.type}</span></span><span class="event-count">${state.registered.includes(e.id)?1:0} / ${e.cap}</span><span class="event-status">${pill(state.registered.includes(e.id)?'Вы записаны':'Открыт',state.registered.includes(e.id)?'gold':'green')}</span></button>`).join('')||empty('Турниры не найдены','Попробуйте другую дату или название.',btn('Сбросить фильтры','clear-filters','secondary small'))}</div>`;}
function eventCards(items){return `<div class="cards">${items.map(e=>`<article class="panel event-card"><div class="event-card-top"><span>${e.type==='Лига'?'ЛИГИ SRP':e.type==='Сателлит'?'САТЕЛЛИТ':'MILLI CLUB'}</span><span class="suit" aria-hidden="true">♠</span></div><div class="event-card-body"><h3>${e.name}</h3><div class="event-meta">Холдем · Казань</div><div class="card-facts"><span>${e.date} · ${e.time}</span><span>${state.registered.includes(e.id)?1:0} / ${e.cap}</span></div><button class="${state.registered.includes(e.id)?'secondary':'primary'} block" data-action="open-event" data-value="${e.id}">${e.route?'Исследовать':state.registered.includes(e.id)?'Моя запись':'Открыть турнир'}</button></div></article>`).join('')}</div>`;}
function structureTable(){return `<div class="table-wrap"><table class="data-table"><thead><tr><th>Ур.</th><th class="num">SB</th><th class="num">BB</th><th class="num">Ante</th><th class="num">Мин.</th></tr></thead><tbody>${blinds.map((b,i)=>`<tr><td>${i+1}</td>${b.map((n,j)=>`<td class="num">${num(n)}${j===3?':00':''}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function participantTable(league=false){if(league||!state.registered.includes(state.selected))return empty('Участников пока нет',league?'Состав участников появится после формирования списка.':'Будьте первым участником этого турнира.','',true);return `<table class="data-table"><thead><tr><th>Игрок</th><th class="num">Клуб</th></tr></thead><tbody><tr><td>${avatar()} ${esc(state.nick)}</td><td class="num">Milli Club</td></tr></tbody></table>`;}
function registerButton(){const e=events[state.selected];if(e.route)return link(e.route,'Исследовать лигу','primary block');return btn(state.registered.includes(e.id)?'Отменить запись':'Записаться на турнир',state.registered.includes(e.id)?'cancel-registration':'register-event',state.registered.includes(e.id)?'secondary block':'primary block');}
function eventDetail(){const e=events[state.selected];return `<aside class="panel event-detail"><div class="detail-art"><div class="eyebrow">${e.type} · SRP</div><h2>${e.name}</h2><p>Milli Club · Казань</p><span class="art-symbol" aria-hidden="true">♠</span></div><div class="detail-body">${pill(state.registered.includes(e.id)?'Вы записаны':'Регистрация открыта',state.registered.includes(e.id)?'gold':'green')}<dl class="facts"><div><dt>Дата</dt><dd>${e.date}.2026</dd></div><div><dt>Начало</dt><dd>${e.time}</dd></div><div><dt>Участники</dt><dd>${state.registered.includes(e.id)?1:0} / ${e.cap}</dd></div><div><dt>Вид игры</dt><dd>${e.game}</dd></div></dl><div class="detail-tabs">${['О турнире','Участники','Структура'].map(t=>`<button data-action="detail-tab" data-value="${t}" class="${state.detailTab===t?'active':''}">${t}</button>`).join('')}</div><div class="detail-copy">${state.detailTab==='О турнире'?'<strong>Milli Club · Казань</strong><p>ул. Николая Ершова, 1А</p>':state.detailTab==='Участники'?participantTable():`<p>25 уровней · SB / BB / Ante</p>${link('tournament','Смотреть структуру','text-link')}`}</div>${registerButton()}${btn('Подробности турнира','event-details','ghost block small')}</div></aside>`;}
function home(){return mediaBanner()+link('map',`<div><div class="eyebrow">SRP В ПОЕЗДКЕ</div><h2>Новый город. Своя игра.</h2><p>Клубы сети на карте и маршрут к игре</p></div>${ic('pin')}`,'trip-entry')+`<div class="section-head"><h2>Ближайшие турниры</h2>${link('tournaments','Все турниры')}</div>${eventCards(events.slice(0,3))}<div class="section-head"><h2>Лиги SRP</h2>${link('leagues','Все лиги')}</div><div class="grid2">${leagueMedia('leagues','Лига Городов','10–11 октября · Казань','zemlya.mp4','zemlya-poster.jpg')}${leagueMedia('ambassadors','Лига Амбассадоров','Амбассадорская покерная лига · Скоро','ambassador.mp4','ambassador-poster.jpg')}</div><div class="grid2" style="margin-top:16px">${link('about',`<div><h3>SRP · Наша сеть</h3><p>Клубы, правила и сообщество</p></div>${ic('network')}`,'panel link-panel')}${link('support',`<div><h3>QA · Поддержка</h3><p>Вопросы по приложению</p></div>${ic('help')}`,'panel link-panel')}</div>`;}

function tournaments(){return pageHead('Турниры','Milli Club · Расписание',pill('7–11 октября'))+`<div class="toolbar">${searchBox('Найти турнир')}<select data-select="date" aria-label="Дата турнира">${['Все даты','07.10','08.10','09.10','10.10','11.10'].map(d=>`<option ${state.dateFilter===d?'selected':''}>${d}</option>`).join('')}</select><span class="count" id="event-count">${visibleEvents().length} событий</span></div><div class="toolbar"><div class="filter-chips">${['Все','Клубный','Лига','Сателлит','Мои'].map(t=>`<button data-action="event-filter" data-value="${t}" class="${state.filter===t?'active':''}" aria-pressed="${state.filter===t}">${t==='Клубный'?'Клубные':t==='Лига'?'Лиги':t==='Сателлит'?'Сателлиты':t}</button>`).join('')}</div></div><div class="split"><div id="event-list">${eventRows()}</div>${eventDetail()}</div>`;}
function tournament(){const e=events[state.selected];return back('tournaments','Все турниры')+`<div class="event-art"><div class="eyebrow">${e.type} · Холдем</div><h1>${e.name}</h1><p class="subheading">Milli Club · Казань</p><span class="art-symbol" aria-hidden="true">♠</span></div><div class="event-page-grid"><div class="panel event-page-body">${tabline(['О турнире','Участники','Структура'],state.detailTab,'detail-tab')}<div>${state.detailTab==='Структура'?structureTable():state.detailTab==='Участники'?participantTable():`<div class="info-block"><h3>Когда</h3><p>${e.date}.2026, ${e.time}</p></div><div class="info-block"><h3>Локация</h3><p>Казань, ул. Николая Ершова, 1А</p>${btn('Открыть локацию','location','secondary small')}</div><div class="info-block"><h3>Вид игры</h3><p>${e.game} · Холдем</p></div>`}</div></div><aside class="panel panel-pad">${pill(state.registered.includes(e.id)?'Вы записаны':'Регистрация открыта',state.registered.includes(e.id)?'gold':'green')}<dl class="facts"><div><dt>Дата</dt><dd>${e.date}.2026</dd></div><div><dt>Начало</dt><dd>${e.time}</dd></div><div><dt>Участники</dt><dd>${state.registered.includes(e.id)?1:0} / ${e.cap}</dd></div><div><dt>Клуб</dt><dd>Milli Club</dd></div></dl>${registerButton()}<div class="event-side-info"><div class="note">Запись сохраняется в личном кабинете.</div>${link('history','Мои турниры','ghost block small')}</div></aside></div>`;}
function completed(){const p=past[state.pastIndex];return back('history','История турниров')+pageHead(p[0],'Завершённый турнир · '+p[1]+'.2026',pill('Завершён'))+`<div class="event-page-grid"><div class="panel event-page-body">${tabline(['О турнире','Лидерборд','Очки'],state.completedTab||'О турнире','completed-tab')}${state.completedTab==='Лидерборд'?`<div class="note">Состав строк демонстрационный. Ваше место взято из истории SRP.</div><table class="data-table"><thead><tr><th>Место</th><th>Игрок</th><th class="num">Результат</th></tr></thead><tbody>${players.slice(0,3).map((p,i)=>`<tr><td class="rank">${i+1}</td><td>${link('player',p[0],'',`data-player="${i}"`)}</td><td class="num">Топ-${i+1}</td></tr>`).join('')}<tr style="background:#36242a"><td class="rank">${p[2]}</td><td>${esc(state.nick)}</td><td class="num">${p[2]} место</td></tr></tbody></table>`:state.completedTab==='Очки'?`<div class="stats-grid" style="grid-template-columns:1fr 1fr"><div class="stat"><b>710,41</b><span>Пулл очков</span></div><div class="stat"><b>1 032</b><span>Средний рейтинг турнира</span></div></div>`:`<div class="info-block"><h3>Когда</h3><p>${p[1]}.2026 · 18:00</p></div><div class="info-block"><h3>Что вас ждёт</h3><p>Баунти турнир! За выбивание игрока даётся 1 баунти с 5 XP.</p></div><div class="info-block"><h3>Локация</h3><p>Казань, ул. Николая Ершова, 1А</p></div><div class="info-block"><h3>Вид игры</h3><p>KO</p></div>`}</div><aside class="panel panel-pad"><div class="eyebrow">Ваш результат</div><div class="stat" style="border:0;padding:12px 0 23px"><b>${p[2]} место</b><span>Холдем · ${p[1]}.2026</span></div>${link('statistics','Моя статистика','secondary block')}</aside></div>`;}
function history(){const upcoming=state.registered.map(i=>events[i]);return accountNav('history')+pageHead('История турниров','Мои игры',pill('79 игр'))+tabs(['Мои','Все'],state.historyTab,'history-tab')+`${upcoming.length?`<div class="section-head"><h2>Предстоящие</h2></div>${eventCards(upcoming)}`:''}<div class="section-head"><h2>${state.historyTab==='Мои'?'Сыгранные турниры':'Архив турниров клуба'}</h2></div><div class="panel table-wrap"><table class="data-table"><thead><tr><th>Турнир</th><th>Дата</th><th class="num">Место</th></tr></thead><tbody>${past.slice(0,state.historyLimit).map((p,i)=>`<tr><td>${link('completed',p[0],'',`data-past="${i}"`)}<div class="event-meta">Холдем · Milli Club</div></td><td>${p[1]}</td><td class="num">${p[2]}</td></tr>`).join('')}</tbody></table></div>${state.historyLimit<past.length?`<div style="text-align:center;margin-top:18px">${btn('Показать ещё','more-history','secondary')}</div>`:''}<div class="note">В прототипе — фрагмент истории для проверки переходов. Рабочая версия загрузит все записи.</div>`;}
function leagues(){return pageHead('Лиги SRP','Сезон 2026')+tabs(['Городов','Чемпионов','Рейтинга'],state.league,'league')+(state.league==='Городов'?`<div class="section-head"><h2>Ближайшие события</h2></div>${eventCards(events.slice(6,8))}`:state.league==='Чемпионов'?`<div class="toolbar">${clubSelect()}<span class="count">Отбор представителей клуба</span></div><div class="round-list">${[1,2,3,4,5,6].map(n=>`<div class="round-row"><div><div class="eyebrow">Тур ${n}</div><h3>${n<4?'Финал':'Раунды и финал'}</h3><div class="muted" style="margin-top:5px">${n===1?'Олег Дегтярев':n===2?'Ильдар Байтимиров':n===3?'Победитель не определён':'Сезон 2026'}</div></div><button class="secondary" data-action="champion-round" data-value="${n}">Открыть</button></div>`).join('')}</div>`:`<div class="toolbar">${clubSelect()}<span class="count">Год клуба</span></div><div class="panel link-panel"><div><div class="eyebrow">Октябрь 2026</div><h2>Топ-1 · Амир Нуриев</h2><p>Путь к финальному столу клуба</p></div>${link('rating-event','Открыть','primary')}</div>`);}
function leagueContent(kind){const names=kind==='cities'?['О турнире','В финал','Участники','Структура']:['О турнире','Сетка','Победители','Участники','Структура'];const tab=names.includes(state.leagueTab)?state.leagueTab:'О турнире';let body='';if(tab==='Структура')body=structureTable();else if(tab==='Участники')body=participantTable(true);else if(tab==='В финал')body=empty('Отбор ещё не завершён','Список прошедших появится после завершения отбора.');else if(tab==='Победители')body=empty('Победитель ещё не определён','Результат появится после завершения финала.');else if(tab==='Сетка')body=`<div class="bracket"><div class="bracket-col"><h3>Отбор клуба</h3><div class="bracket-item winner">Амир Нуриев<small>Топ-1 · Октябрь 2026</small></div><div class="bracket-item">Победитель отборочного<small>Октябрь 2026</small></div><div class="bracket-item">Топ-1<small>Ноябрь 2026</small></div><div class="bracket-item">Победитель отборочного<small>Ноябрь 2026</small></div></div><div class="bracket-col"><h3>Финал клуба</h3><div class="bracket-item">Milli Club · Казань<small>Победитель финального стола</small></div></div><div class="bracket-col"><h3>Финал сети</h3><div class="bracket-item">Победители клубов SRP<small>Финал года клубов</small></div></div></div>`;else{const title=kind==='cities'?'Лига Городов':kind==='champions'?'Лига Чемпионов':'Лига Рейтинга';const text=kind==='cities'?'Главный турнир месяца сети SRP. За одним столом встречаются лучшие игроки всех клубов: города спорят за титул, а победитель становится чемпионом Лиги Городов.':kind==='rating'?'На протяжении зачётного года игроки клуба соревнуются за лидерство в ежемесячном рейтинге. Победитель месяца получает место на финальном столе клуба. Победитель финала клуба получает билет на финал года клубов SRP.':'Этапы отбора определяют игрока, который представляет клуб. Сохранены туры, раунды и финалы.';body=`<details class="disclosure" open><summary>Что такое ${title}</summary><p>${text}</p></details>${kind==='cities'?`<details class="disclosure" open><summary>Когда</summary><p>${state.selected===7?'11 октября, 14:00':'10 октября, 16:00'}</p></details><details class="disclosure" open><summary>Локация</summary><p>Казань, ул. Николая Ершова, 1А</p></details>`:''}`;}return tabline(names,tab,'league-tab')+body;}
function leagueEvent(kind){const title=kind==='cities'?`Лига Городов · ${state.selected===7?'Final':'1A'}`:kind==='champions'?`Лига Чемпионов · Тур ${state.round}`:'Лига Рейтинга';return back('leagues','Лиги SRP')+`<div class="event-art"><div class="eyebrow">${kind==='cities'?'Чемпионат клубов · Казань':'Milli Club · Казань'}</div><h1>${title}</h1><p class="subheading">${kind==='cities'?'Главный турнир месяца':kind==='champions'?'Отбор клуба':'Битва сильнейших'}</p></div><div class="panel event-page-body">${kind==='rating'?`<div style="margin-bottom:15px">${pill('Идёт формирование игроков','gold')}</div>`:''}${kind==='champions'?`<div class="toolbar"><select data-select="round-stage" aria-label="Раунд">${['Финал','Раунд 1','Раунд 2','Раунд 3','Раунд 4','Раунд 5','Раунд 6','Раунд 7','Раунд 8'].map(t=>`<option ${state.roundStage===t?'selected':''}>${t}</option>`).join('')}</select></div>`:''}${leagueContent(kind)}</div>`;}
function visibleClubs(){return clubData.map((c,i)=>({c,i})).filter(({c})=>(state.clubCity==='Все города'||c[1]===state.clubCity)&&c.join(' ').toLowerCase().includes(state.search.toLowerCase()));}
function clubCityFilter(){return `<select aria-label="Город" data-select="club-city">${['Все города',...new Set(clubData.map(c=>c[1]).sort((a,b)=>a.localeCompare(b,'ru')))].map(city=>`<option value="${esc(city)}" ${state.clubCity===city?'selected':''}>${esc(city)}</option>`).join('')}</select>`;}
function clubCards(){let cs=visibleClubs();if(state.clubsTab==='Новые')return empty('Новые клубы','Список новых клубов не загрузился на текущем сайте. Экран сохранён для сверки.');return `<div class="club-grid">${cs.map(({c,i})=>`<article class="panel club-card"><div class="club-card-banner"><span class="club-initials">${esc(initials(c[0]))}</span>${i===state.club?pill('Мой клуб','gold'):ic('pin')}</div><div class="club-card-body"><div class="eyebrow">${esc(c[1])}</div><h3>${esc(c[0])}</h3><p>Клуб сети SRP</p>${link('club','О клубе','secondary block',`data-club="${i}"`)}</div></article>`).join('')||empty('Клубы не найдены','Попробуйте другой город или название.')}</div>`;}
function clubs(){return pageHead('Наши клубы','Федеральная сеть SRP')+link('map',`<div><div class="eyebrow">SRP В ПОЕЗДКЕ</div><h2>Едешь в другой город?</h2><p>Найди свой клуб и спланируй маршрут</p></div>${ic('pin')}`,'trip-entry')+`<div class="tabs">${['Все','Новые','Карта'].map(t=>`<button data-action="clubs-tab" data-value="${t}" class="${state.clubsTab===t?'active':''}">${t}</button>`).join('')}</div><div class="toolbar">${searchBox('Клуб или город','clubs')}${clubCityFilter()}<span class="count" id="club-count">Найдено: ${visibleClubs().length} из ${clubData.length} клубов</span></div><div id="club-list">${clubCards()}</div>`;}
function club(){const i=state.clubDetail??state.club,c=clubData[i];return back('clubs','Наши клубы')+`<div class="event-art"><div class="eyebrow">${esc(c[1])} · SRP</div><h1>${esc(c[0])}</h1><p class="subheading">Клуб спортивно-развлекательного покера</p></div><div class="grid2"><div class="panel panel-pad"><h2>О клубе</h2><div class="info-line"><span>Город</span><strong>${esc(c[1])}</strong></div><div class="info-line"><span>Формат</span><strong>Покер не на деньги</strong></div><div class="info-line"><span>Адрес</span><strong>${i===0?'ул. Николая Ершова, 1А':'Уточняется у клуба'}</strong></div><div style="margin-top:20px">${btn(i===state.club?'Ваш клуб':'Выбрать клуб','choose-club',i===state.club?'secondary block':'primary block',`data-value="${i}"`)}</div></div><div class="panel panel-pad"><h2>События и рейтинг</h2><div style="display:grid;gap:12px;margin-top:21px">${link('tournaments','Турниры клуба','secondary block')}${link('rating','Рейтинг игроков','secondary block')}${link('map','Карта клубов','secondary block')}</div><div class="note">Сведения клуба, кроме Milli Club, требуют проверки: каталог текущего сайта не загрузился.</div></div></div>`;}
function tripDateValid(v){return /^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(Date.parse(v+'T00:00:00Z'))&&new Date(v+'T00:00:00Z').toISOString().slice(0,10)===v;}
function tripCalendar(item){
 if(!tripDateValid(item.date))return '';
 const c=clubData[item.club],next=new Date(item.date+'T00:00:00Z');next.setUTCDate(next.getUTCDate()+1);
 const safe=v=>String(v).replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');
 const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//SRP Prototype//Trip Plan//RU','CALSCALE:GREGORIAN','BEGIN:VEVENT',`UID:trip-${item.club}-${item.date}@srp-prototype`,`DTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'')}`,`DTSTART;VALUE=DATE:${item.date.replace(/-/g,'')}`,`DTEND;VALUE=DATE:${next.toISOString().slice(0,10).replace(/-/g,'')}`,`SUMMARY:${safe('Сходить в '+c[0]+' · '+c[1])}`,`LOCATION:${safe(item.club===0?mapQuery(0):c[1])}`,`DESCRIPTION:${safe('Личный план посещения. Запись в клуб не оформлена. Уточните расписание и адрес до поездки.')}`,`URL:https://yandex.ru/maps/?text=${encodeURIComponent(mapQuery(item.club))}`,'BEGIN:VALARM','TRIGGER:-PT12H','ACTION:DISPLAY','DESCRIPTION:Проверь план посещения клуба SRP','END:VALARM','END:VEVENT','END:VCALENDAR'];
 const fold=line=>{let out='',bytes=0;for(const ch of line){const n=encodeURIComponent(ch).replace(/%[0-9A-F]{2}/g,'x').length;if(bytes+n>73){out+='\r\n ';bytes=1;}out+=ch;bytes+=n;}return out;};
 return lines.map(fold).join('\r\n')+'\r\n';
}
function tripPlan(){const items=state.tripPlan||[];return `<section class="panel trip-plan"><header><div><div class="eyebrow">ТВОИ БУДУЩИЕ ИГРЫ</div><h2>Мой план поездки <span>${items.length}</span></h2></div>${ic('star')}</header>${items.length?`<div class="trip-plan-list">${items.map(item=>{const c=clubData[item.club];return `<article class="trip-plan-item"><button class="trip-plan-open" data-action="trip-plan-open" data-value="${item.club}"><strong>${esc(c[0])}</strong><small>${esc(c[1])} · ${item.date?esc(item.date.split('-').reverse().join('.')):'Выбери дату посещения'}</small></button><div class="trip-plan-controls">${item.date?`<a class="secondary small" href="data:text/calendar;charset=utf-8,${encodeURIComponent(tripCalendar(item))}" download="srp-trip-${item.club}-${item.date}.ics" aria-label="В календарь: ${esc(c[0])}">В календарь ↓</a>`:''}${btn(ic('close'),'trip-plan-remove','icon-button',`data-value="${item.club}" aria-label="Убрать из плана: ${esc(c[0])}"`)}</div></article>`;}).join('')}</div>`:'<p class="trip-plan-empty">Сохрани интересный клуб — он останется здесь до следующей поездки.</p>'}<small class="trip-plan-note">План сохраняется на этом устройстве. Это личное напоминание, а не запись на турнир.</small></section>`;}
function mapQuery(i){const c=clubData[i];return i===0?'Казань, ул. Николая Ершова, 1А':c.join(' ');}
function map(){
 const city=state.tripCity||clubData[state.mapClub][1];
 const list=clubData.map((c,i)=>({c,i})).filter(({c})=>c[1]===city);
 if(!list.some(({i})=>i===state.mapClub))state.mapClub=list[0].i;
 const c=clubData[state.mapClub],q=encodeURIComponent(mapQuery(state.mapClub)),planned=(state.tripPlan||[]).find(p=>p.club===state.mapClub);
 const route=mode=>`https://yandex.ru/maps/?mode=routes&rtext=~${q}&rtt=${mode}`;
 return back('clubs','Все клубы')+`<section class="trip-hero"><div><div class="eyebrow">SRP В ПОЕЗДКЕ</div><h1>Новый город. Своя игра.</h1><p>Найди клуб сети, посмотри локацию и спланируй вечер.</p></div><span aria-hidden="true">${ic('pin')}</span></section><div class="trip-toolbar"><label class="field">Куда едешь?<select data-select="trip-city" aria-label="Город поездки">${[...new Set(clubData.map(c=>c[1]))].sort((a,b)=>a.localeCompare(b,'ru')).map(v=>`<option ${v===city?'selected':''}>${esc(v)}</option>`).join('')}</select></label><div><strong>${list.length} ${list.length===1?'клуб':'клуба'}</strong><small>в справочнике SRP · ${esc(city)}</small></div></div><div class="trip-layout"><div class="trip-map"><iframe title="Карта выбранного клуба" src="https://yandex.ru/map-widget/v1/?text=${q}&z=14" loading="lazy" allowfullscreen></iframe><a class="trip-map-fallback" href="https://yandex.ru/maps/?text=${q}" target="_blank" rel="noopener noreferrer">Открыть большую карту ↗</a></div><aside class="trip-details"><div class="trip-clubs" aria-label="Клубы города">${list.map(({c,i})=>`<button class="trip-club ${state.mapClub===i?'active':''}" data-action="map-club" data-value="${i}" aria-pressed="${state.mapClub===i}">${ic('pin')}<span><strong>${esc(c[0])}</strong><small>${i===0?'ул. Николая Ершова, 1А':'Адрес уточняется'}</small></span>${ic('chevron')}</button>`).join('')}</div><section class="panel panel-pad trip-selected"><div class="eyebrow">ТВОЯ ОСТАНОВКА</div><h2>${esc(c[0])}</h2><p>${esc(city)} · Покер не на деньги</p>${state.mapClub===0?`<p>ул. Николая Ершова, 1А</p><h3>Как добраться?</h3><div class="trip-routes">${[['auto','На машине'],['mt','Транспорт'],['pd','Пешком']].map(([m,t])=>`<a class="secondary" href="${route(m)}" target="_blank" rel="noopener noreferrer">${t} ↗</a>`).join('')}</div><small>Начальную точку выбери в Яндекс Картах.</small>`:`<p class="trip-address-note">В справочнике пока нет точного адреса. Проверь найденную организацию на карте перед поездкой.</p><a class="secondary block" href="https://yandex.ru/maps/?text=${q}" target="_blank" rel="noopener noreferrer">Найти клуб в Яндекс Картах ↗</a>`}<div class="trip-plan-editor"><label class="field">Когда хочешь зайти?<input type="date" aria-label="Дата посещения" data-trip-date="${state.mapClub}" value="${esc(planned?.date||'')}"></label>${btn(planned?'✓ Сохранено в поездку':'Сохранить в поездку','trip-plan-save',planned?'secondary block':'primary block',`data-value="${state.mapClub}"`)}<small>Можно сохранить клуб сейчас и выбрать дату позже.</small></div><button class="secondary block" data-action="map-open-club">О клубе</button>${state.mapClub===0?link('tournaments','Посмотреть турниры','ghost block'):''}</section></aside></div>${tripPlan()}<p class="note">Клубы из каталога макета. Результаты поиска на карте предоставлены Яндексом; совпадения нужно проверить.</p>`;
}

function ratingRows(){return players.map((p,i)=>({p,i})).filter(({p})=>p[0].toLowerCase().includes(state.search.toLowerCase())).map(({p,i})=>`<tr><td class="rank">${i+1}</td><td>${link('player',`<span class="avatar">${initials(p[0])}</span>${esc(p[0])}`,'player-link',`data-player="${i}"`)}</td><td class="num">${num(p[1])}</td></tr>`).join('');}
function rating(){return pageHead('Рейтинг игроков','SRP · Сезон 2026')+tabs(['Мой клуб','Сеть','Неделя'],state.ratingTab,'rating-tab')+`<div class="toolbar">${searchBox('Найти игрока','players')}<span class="count">${state.ratingTab==='Мой клуб'?esc(clubData[state.club].join(' · ')):state.ratingTab==='Сеть'?'Федеральный рейтинг':'Рейтинг недели'}</span></div><div class="panel table-wrap"><table class="data-table"><thead><tr><th>Место</th><th>Игрок</th><th class="num">Рейтинг</th></tr></thead><tbody id="rating-body">${ratingRows()}</tbody></table></div>${state.ratingTab!=='Мой клуб'?'<div class="note">В этой вкладке использованы демонстрационные строки рейтинга Milli Club. Сортировка и состав требуют данных API.</div>':''}`;}
function player(){const p=players[state.player];return back('rating','Рейтинг игроков')+pageHead('Профиль игрока','SRP')+`<section class="profile-hero">${avatar(p[0],true)}<div><h2>${esc(p[0])}</h2><p class="muted">Milli Club · Казань</p></div><div class="head-actions">${pill(num(p[1])+' рейтинга','gold')}</div></section><div class="profile-menu">${[['player-history','history','Турниры','История игр'],['player-achievements','trophy','Достижения','Награды'],['player-statistics','chart','Статистика','Показатели']].map(([r,i,t,p])=>link(r,ic(i)+`<h3>${t}</h3><p>${p}</p>`,'panel')).join('')}</div>`;}
function playerClubTabs(){return tabs(['Milli Club · Казань','СРП · Набережные Челны'],state.publicClub||'Milli Club · Казань','public-club');}
function playerHistory(){const name=players[state.player][0];return back('player','Профиль игрока')+pageHead('Турниры',esc(name))+playerClubTabs()+`${state.publicClub==='СРП · Набережные Челны'?empty('История другого клуба','Компоновка выбора клуба сохранена. Данные второго клуба требуют API.'):state.player===0?`<div class="panel table-wrap"><table class="data-table"><thead><tr><th>Турнир</th><th>Дата</th><th class="num">Место</th></tr></thead><tbody>${publicPast.map((p,i)=>`<tr><td><button class="text-link" data-action="public-result" data-value="${i}">${p[0]}</button><div class="event-meta">Холдем</div></td><td>${p[1]}</td><td class="num">${p[2]}</td></tr>`).join('')}</tbody></table></div>`:empty('История игрока','Данные будут загружаться из публичного профиля SRP.')}`;}
function playerAchievements(){return back('player','Профиль игрока')+pageHead('Достижения',esc(players[state.player][0]))+tabs(['Обычные','Редкие'],state.achTab,'ach-tab')+`<div class="note">Компоновка коллекции показана на примере. Прогресс другого игрока загружается отдельно от вашего.</div>`+achievementCards(state.achTab==='Обычные'?ordinary:rare,0);}
function playerStatistics(){return back('player','Профиль игрока')+pageHead('Статистика',esc(players[state.player][0]))+playerClubTabs()+`<div class="stats-grid">${(state.player===0&&state.publicClub!=='СРП · Набережные Челны'?[[98,'Игр'],[1,'Топ-1'],[3,'Топ-3'],[11,'Топ-9']]:[['—','Игр'],['—','Топ-1'],['—','Топ-3'],['—','Топ-9']]).map(([n,t])=>`<div class="stat"><b>${n}</b><span>${t}</span></div>`).join('')}</div><div class="grid2"><div class="panel panel-pad"><h2>Лучшие турниры · Топ-9</h2><div class="note">Лига Городов · Понедельник · Феникс · Короткий турнир · Sit&amp;Go · Кубковый турнир · Нокаут PKO · Mystery · LADY’S EVENT</div>${empty('Результаты по типам турниров','График загружается из статистики игрока.','',true)}</div><div class="panel panel-pad"><h2>Динамика мест</h2><div class="bar-chart" role="img" aria-label="Последние десять мест Амира Нуриева из истории турниров">${publicPast.slice().reverse().map(p=>`<div class="bar-wrap"><span class="bar-value">${p[2]}</span><div class="bar" style="height:${Math.max(8,150-p[2]*1.5)}px"></div></div>`).join('')}</div><div class="note">Демонстрация на публичных результатах Амира Нуриева. Полная динамика загружается из API.</div></div></div>`;}
function profile(){return pageHead('Мой аккаунт','Milli Club · Казань',link('settings',ic('settings')+'Настройки','secondary'))+`<section class="profile-hero">${avatar(state.nick,true)}<div><h2>${esc(state.nick)}</h2><p class="muted">${esc(clubData[state.club].join(' · '))}</p></div><div class="head-actions">${link('notifications',ic('bell')+'Уведомления','secondary')}</div></section><div class="profile-menu">${[['history','history','Турниры','История игр и результаты'],['achievements','trophy','Достижения','Награды и прогресс'],['statistics','chart','Статистика','Показатели и динамика'],['broadcast','play','Трансляция','Карточка игрока и анкета'],['push-settings','bell','Уведомления','Напоминания и события'],['settings','settings','Профиль','Фото и контактные данные']].map(([r,i,t,p])=>link(r,ic(i)+`<h3>${t}</h3><p>${p}</p>`,'panel')).join('')}</div>${link('loyalty',`<div><h3>Карта лояльности</h3><p>Раздел в разработке</p></div>${pill('Скоро','gold')}`,'loyalty')}<div class="section-head"><h2>Приложение</h2></div><div class="toolbar">${link('updates','v4.7.0 · Что нового','secondary small')}${link('privacy','Конфиденциальность','ghost small')}${link('consent','Обработка данных','ghost small')}</div>`;}
function achievementCards(data,offset){return `<div class="achievements-grid">${data.map((a,i)=>`<button class="achievement-card ${a.now<a.max?'locked':''}" data-action="achievement" data-value="${offset+i}"><span class="medal">${ic(a.level?'star':'trophy')}</span><strong>${a.name}</strong><small>${a.level?'Уровень '+a.level:a.desc}</small><small>${a.now>=a.max?'Получено':`${a.now} / ${a.max}`}</small><div class="progress-track" role="progressbar" aria-label="Прогресс достижения" aria-valuenow="${Math.min(a.now,a.max)}" aria-valuemin="0" aria-valuemax="${a.max}"><div class="progress-fill" style="width:${Math.min(100,a.now/a.max*100)}%"></div></div></button>`).join('')}</div>`;}
function achievements(){const data=state.achTab==='Обычные'?ordinary:rare;const groups=[...new Set(data.map(a=>a.group))];return accountNav('achievements')+pageHead('Достижения','Мои награды')+tabs(['Обычные','Редкие'],state.achTab,'ach-tab')+groups.map(group=>{const list=data.filter(a=>a.group===group);const percent={'Победы и места':67,'Активность':25,'Баунти хантер':0,'Истинный регуляр':33,'Олигарх':67}[group];return `<div class="achievement-group-head"><strong>${group}</strong><span>${percent}% коллекции</span></div>${achievementCards(list,data.indexOf(list[0]))}`;}).join('');}
function statistics(){const places=past.slice().reverse().map(p=>p[2]);const xs=places.map((_,i)=>56+i*42);const ys=places.map(n=>55+n*1.05);return accountNav('statistics')+pageHead('Статистика','Показатели игрока')+`<div class="stats-grid">${[[79,'Игр'],[1,'Топ-1'],[2,'Топ-3'],[7,'Топ-9']].map(([n,t])=>`<div class="stat"><b>${n}</b><span>${t}</span></div>`).join('')}</div><div class="grid2"><div class="panel chart-panel"><h2>Лучшие турниры · Топ-9</h2><div class="bar-chart" role="img" aria-label="Демонстрационная компоновка лучших результатов по типам турниров">${[3,2,1,1].map((n,i)=>`<div class="bar-wrap"><span class="bar-value">${n}</span><div class="bar" style="height:${n*45}px"></div></div>`).join('')}</div><div class="chart-labels"><span>Лига Городов</span><span>Феникс</span><span>Sit&amp;Go</span><span>Нокаут PKO</span></div><div class="note">Распределение показано для примера компоновки.</div></div><div class="panel chart-panel"><h2>Динамика мест</h2><svg class="line-chart" viewBox="0 0 570 235" role="img" aria-label="Места в последних 12 турнирах из истории SRP"><text x="8" y="20">Место</text>${[1,50,100].map(n=>`<line x1="44" y1="${55+n*1.05}" x2="535" y2="${55+n*1.05}" stroke="#343945"/><text x="8" y="${59+n*1.05}">${n}</text>`).join('')}<polyline points="${xs.map((x,i)=>`${x},${ys[i]}`).join(' ')}" fill="none" stroke="#ed5964" stroke-width="2.5"/>${xs.map((x,i)=>`<circle cx="${x}" cy="${ys[i]}" r="4" fill="#ed5964"><title>${past.slice().reverse()[i][1]}: ${places[i]} место</title></circle>`).join('')}<text x="43" y="216">14 сентября</text><text x="456" y="216">6 октября</text></svg><div class="note">Чем ниже число, тем выше результат.</div></div></div><div class="section-head"><h2>По турнирам</h2>${link('history','Открыть историю')}</div><div class="panel table-wrap"><table class="data-table"><thead><tr><th>Турнир</th><th>Дата</th><th class="num">Место</th></tr></thead><tbody>${past.slice(0,5).map((p,i)=>`<tr><td>${link('completed',p[0],'',`data-past="${i}"`)}</td><td>${p[1]}</td><td class="num">${p[2]}</td></tr>`).join('')}</tbody></table></div>`;}
function settingsNav(active){return `<nav class="panel form-sidebar" aria-label="Настройки">${[['settings','user','Профиль'],['broadcast','play','Трансляция'],['push-settings','bell','Уведомления']].map(([r,i,t])=>link(r,ic(i)+t,r===active?'active':'')).join('')}</nav>`;}
function settings(){return accountNav('settings')+pageHead('Настройки','Аккаунт SRP')+`<div class="form-layout">${settingsNav('settings')}<div class="form-stack"><form id="profile-form" class="panel form-panel"><h2>Данные профиля</h2><div class="avatar-upload">${avatar(state.nick,true)}<div><label class="secondary small" for="avatar-file">${ic('upload')} Загрузить фото</label><input id="avatar-file" type="file" accept="image/*" hidden><div class="note">Фото профиля</div></div></div><div class="form-grid">${field('Никнейм','nick','text',state.nick,'required maxlength="60"')}${field('Дата рождения','birth','date',state.birth||'')}</div><button type="submit" class="primary" style="margin-top:20px">Сохранить профиль</button></form><div class="panel form-panel"><h2>Контакты</h2><div class="form-grid"><label class="field full">Почта<div class="field-action"><input id="contact-email" type="email" placeholder="name@example.com" value="${esc(state.email||'')}">${btn(state.emailVerified?'Подтверждена':'Получить код','verify-email','secondary')}</div></label><label class="field full">Телефон<div class="field-action"><input id="contact-phone" type="tel" placeholder="+7 (___) ___-__-__" value="${esc(state.phone||'')}">${btn(state.phoneVerified?'Подтверждён':'Подтвердить звонком','verify-phone','secondary')}</div></label></div><div class="note">Используйте вымышленные контакты: это демонстрационная форма.</div></div><form id="password-form" class="panel form-panel"><h2>Пароль</h2><div class="form-grid">${field('Сейчас','current','password','','autocomplete="off"')}${field('Новый','newPassword','password','','required minlength="8" autocomplete="off"')}</div><div class="note">Если пароля ещё не было, текущий можно не заполнять.</div><label class="check-line"><input type="checkbox" data-toggle-password>Показать пароли</label><button class="secondary" type="submit" style="margin-top:18px">Обновить пароль</button></form><div class="panel form-panel"><h2>Привязать аккаунт</h2><div class="toolbar">${btn(state.telegramLinked?'Telegram · привязан':'Telegram','link-telegram','secondary')}${btn(state.vkLinked?'VK · привязан':'VK','link-vk','secondary')}${pill('MAX · скоро','gold')}</div></div><div class="panel form-panel"><h2>Приложение</h2><div class="toolbar">${link('install','Установить приложение','secondary')}${link('push-settings','Настроить уведомления','secondary')}</div>${btn(ic('logout')+'Выйти','logout','danger')}</div></div></div>`;}
function broadcast(){return accountNav('settings')+pageHead('Трансляция','Карточка игрока и анкета')+`<div class="form-layout">${settingsNav('broadcast')}<form id="broadcast-form" class="form-stack"><div class="panel form-panel"><h2>Как в эфире</h2><div class="broadcast-card">${avatar(state.nick)}<div><strong id="broadcast-preview-name">${esc([state.broadcast.last,state.broadcast.first].filter(Boolean).join(' ')||'ИГРОК')}</strong><small>КАЗАНЬ</small></div><span class="broadcast-stack">30 K</span></div><div class="form-grid">${field('Фамилия','last','text',state.broadcast.last||'')}${field('Имя','first','text',state.broadcast.first||'')}</div><div style="margin-top:18px"><label class="secondary small" for="broadcast-photo">${ic('upload')} Фото для эфира</label><input id="broadcast-photo" type="file" accept="image/*" hidden></div></div><div class="panel form-panel"><h2>Анкета · Октябрь 2026</h2><div class="form-grid">${questions.map((q,i)=>`<label class="field full">${q} *<textarea name="q${i}" required maxlength="1500">${esc(state.broadcast['q'+i]||'')}</textarea></label>`).join('')}</div><div class="note">Эти ответы увидят в ТВ-трансляции ближайшего месяца Лиги Городов.</div><button type="submit" class="primary block">Сохранить</button></div></form></div>`;}
function pushSettings(){return pageHead('Настройки уведомлений','Приложение SRP')+`<div class="form-layout">${settingsNav('push-settings')}<div class="form-stack"><div class="panel form-panel"><h2>Пуш-уведомления</h2><p class="subheading" style="margin:0 0 15px">Выберите события, о которых хотите узнавать.</p>${[['reminder','Напоминания о турнирах','Начало турнира, на который вы записались.'],['event','События моего клуба','Новые турниры и изменения расписания.'],['result','Результаты и достижения','Рейтинг, результаты и новые награды.'],['promo','Приглашения и новости SRP','Разрешаю присылать рекламные приглашения и предложения сети.']].map(([id,t,p])=>`<label class="switch-row"><span><strong>${t}</strong><p>${p}</p></span><input class="switch" type="checkbox" data-push="${id}" aria-label="${t}" ${state.push[id]?'checked':''}></label>`).join('')}<div class="note">Новые настройки для будущего мобильного приложения. Системное разрешение в прототипе не запрашивается.</div>${btn('Показать пример пуша','sample-push','secondary block')}</div><div class="panel form-panel"><h2>Разрешение устройства</h2><p class="subheading">В рабочем приложении разрешение запрашивается у iOS или Android. Вы можете изменить его в настройках телефона.</p>${btn('Предпросмотр запроса разрешения','permission-preview','secondary block','style="margin-top:20px"')}</div></div></div>`;}
function notifications(){const list=state.demoNotifications||[];return pageHead('Уведомления','События аккаунта',link('push-settings','Настроить','secondary'))+`${list.length?`<div class="round-list">${list.map((n,i)=>`<div class="round-row"><div><div class="eyebrow">${state.readNotifications?'Прочитано':'Новое'}</div><h3>${esc(n.title)}</h3><div class="muted" style="margin-top:5px">${esc(n.text)}</div></div>${link(n.route,'Открыть','secondary small')}</div>`).join('')}</div><div style="margin-top:20px">${btn('Отметить прочитанными','read-notifications','secondary')}</div>`:`<div class="panel">${empty('Уведомлений пока нет','Здесь будут события вашего аккаунта и клуба.',link('tournaments','Посмотреть турниры','primary'))}</div>`}`;}
function about(){return pageHead('Наша сеть','Федеральная сеть SRP')+`<div class="grid2"><div class="panel panel-pad legal-copy"><h2 style="margin-top:0">Что такое SRP</h2><p>Спортивно-развлекательный покер — федеральная сеть клубов, объединяющая игроков и покерные пространства по всей России.</p><p>Интеллектуальная игра, соревнование, стратегия и общение. Участники соревнуются за рейтинг, достижения, статус и возможность представлять свой город на крупных соревнованиях.</p><h2>Правила</h2><p>В клубах SRP не играют на деньги. Игровые фишки не имеют денежной стоимости, денежные ставки и денежные выигрыши запрещены.</p><p>Единые правила поддерживают честную игру, уважение к соперникам и комфортную атмосферу во всех клубах.</p></div><div class="panel panel-pad legal-copy"><h2 style="margin-top:0">Почему мы</h2><p>Федеральный рейтинг, единая система соревнований и Лига Городов позволяют встречаться с игроками из других городов и представлять свой клуб на крупных турнирах.</p><h2>Клубы</h2><p>Москва, Санкт-Петербург, Екатеринбург, Казань, Набережные Челны и другие города. У каждого клуба своя атмосфера и сообщество.</p><div style="margin-top:24px">${link('clubs','Наши клубы','primary')}</div></div></div>`;}
function support(){return pageHead('QA · Поддержка','Вопросы по приложению')+`<div class="grid2"><div class="panel panel-pad"><h2>Частые вопросы</h2><div style="margin-top:22px">${[['Как записаться на турнир?','Откройте «Турниры», выберите событие и нажмите «Записаться». Запись будет доступна в аккаунте.'],['Как посмотреть рейтинг?','В разделе «Рейтинг» доступны вкладки «Мой клуб», «Сеть» и «Неделя».'],['Где результаты моих игр?','Аккаунт → Турниры → Мои. Откройте завершённый турнир, чтобы посмотреть лидерборд и очки.'],['Как подготовить профиль для трансляции?','Аккаунт → Настройки → Трансляция. Заполните карточку игрока и анкету.']].map(([q,a])=>`<details class="disclosure"><summary>${q}</summary><p>${a}</p></details>`).join('')}</div></div><form id="support-form" class="panel form-panel"><h2>Обратиться в поддержку</h2><div class="form-grid" style="margin-top:20px"><label class="field full">Тема<select name="topic"><option>Запись на турнир</option><option>Рейтинг и результаты</option><option>Вход и профиль</option><option>Другое</option></select></label><label class="field full">Сообщение<textarea name="message" required placeholder="Опишите вопрос"></textarea></label></div><button type="submit" class="primary block" style="margin-top:20px">Отправить</button><div class="note">Сценарий обращения предложен для редизайна. На текущем сайте ссылка QA не открыла отдельный экран.</div></form></div>`;}
function updates(){return pageHead('Обновления','Приложение SRP')+`<div class="panel panel-pad"><div class="panel-title"><h2>SRP v4.7.0</h2>${pill('Текущая версия')}</div><p class="muted">Версия подтверждена по ссылке в аккаунте. Полный список изменений нужно перенести из действующего раздела обновлений.</p><div class="note">Экран содержимого предложен для согласования; неподтверждённые релизные заметки не добавлены.</div>${link('profile','Вернуться в аккаунт','secondary')}</div>`;}
function soon(name,desc){return pageHead(name,'SRP · Скоро')+`<div class="panel">${empty(name,desc,pill('В разработке','gold'))}</div>`;}
function install(){return pageHead('Установить приложение','SRP на ваших устройствах')+`<div class="grid3">${[['iPhone','App Store','app-store'],['Android','Google Play / RuStore','android-store'],['Компьютер','Веб-приложение SRP','web-install']].map(([t,p,a])=>`<div class="panel panel-pad"><div class="eyebrow">${t}</div><h2>${p}</h2><p class="subheading">${t==='Компьютер'?'Приложение в браузере, адаптированное под большой экран.':'Турниры, профиль и пуш-уведомления.'}</p>${btn(t==='Компьютер'?'Открыть приложение':'Смотреть установку',a,'secondary block','style="margin-top:22px"')}</div>`).join('')}</div><div class="note">Публикация в магазинах — следующий этап после согласования и разработки.</div>`;}
function legal(kind){const t=kind==='privacy'?'Политика конфиденциальности':'Согласие на обработку персональных данных';return back('profile','Аккаунт')+pageHead(t,'Документы SRP')+`<article class="panel panel-pad legal-copy"><div class="important">В прототипе показана компоновка документа. Юридический текст должен быть перенесён дословно из утверждённой версии SRP.</div><h2 style="margin-top:0">${t}</h2><p>Действующая версия документа доступна на сайте SRP.</p><a class="secondary" style="margin-top:20px" href="https://app.srpclient.ru${kind==='privacy'?'/privacy':'/personal-data-consent'}" target="_blank" rel="noopener">Открыть действующий документ</a><h2>Чтение документа</h2><p>В рабочем приложении документ открывается целиком, с датой редакции и контактами оператора данных. Действие возврата сохраняет предыдущий экран.</p></article>`;}
function authAtmosphere(){return `<section class="auth-art">${srpVideo('home-film-2.mp4','home-film-2-poster.jpg')}<div class="auth-film-shade"></div><div class="auth-film-top"><a href="#welcome" data-route="welcome" class="logo"><img src="${mediaBase}srp-wordmark.svg" alt="СРП"><small>POKER CLUB</small></a><span class="auth-live"><i></i> АТМОСФЕРА НАСТОЯЩЕЙ ИГРЫ</span></div><div class="auth-film-copy"><div class="eyebrow">ЛЮДИ. ЭМОЦИИ. ТВОЯ ИГРА.</div><h1>Твоё место<br>за столом<br> <em>уже ждёт.</em></h1><p>От первого турнира в своём клубе<br>до событий федеральной сети.</p><div class="auth-benefits"><span>${ic('pin')} Клуб рядом</span><span>${ic('calendar')} Живые турниры</span><span>${ic('trophy')} Твой рейтинг</span></div></div><div class="auth-art-bottom"><span>SRP · ФЕДЕРАЛЬНАЯ СЕТЬ</span>${pill('Покер не на деньги','gold')}</div></section>`;}
function welcome(){return authShell(`<div class="eyebrow">ДОБРО ПОЖАЛОВАТЬ В SRP</div><h1>Большая игра.<br>Начни с себя.</h1><p class="subheading">Найди свой клуб, познакомься с игроками и приходи на первый турнир.</p><div class="welcome-steps"><div><span>01</span><p><strong>Выбери клуб</strong><small>Твоя точка входа в игру</small></p></div><div><span>02</span><p><strong>Займи место за столом</strong><small>Расписание и запись в приложении</small></p></div><div><span>03</span><p><strong>Пиши свою историю</strong><small>Рейтинг, результаты, достижения</small></p></div></div>${link('register','Создать аккаунт '+ic('calendar'),'primary block')}${link('login','Уже играешь? Войти','secondary block')}<div class="auth-legal">${link('privacy','Политика конфиденциальности')} · ${link('consent','Обработка данных')}</div>`);}
function authShell(content){return `<div class="auth-layout">${authAtmosphere()}<section class="auth-form"><div class="auth-form-card">${content}</div></section></div>`;}
function login(){return authShell(`<h1>Войдите в аккаунт</h1><p class="subheading">Если аккаунта ещё нет, перейдите к регистрации.</p><div class="tabs">${link('register','Регистрация','ghost')}<button class="active">Вход</button></div><form id="login-form">${field('Почта или телефон','identity','text','','required placeholder="demo@srp.example" autocomplete="off"')}${field('Пароль','password','password','','required placeholder="Любой тестовый пароль" autocomplete="off"')}<div class="auth-links"><label class="check-line"><input type="checkbox" name="remember">Запомнить меня</label>${link('reset','Забыли пароль?','text-link')}</div><label class="check-line" style="margin-top:14px"><input type="checkbox" data-toggle-password>Показать пароль</label><div class="auth-errors" role="alert">${esc(state.authError)}</div><button class="primary block" type="submit">Войти</button></form><div class="auth-divider">Или через приложение</div>${btn('Войти через Telegram','telegram-login','secondary block')}<div class="auth-legal">Тестовый вход. Не вводите настоящий пароль.<br>${link('privacy','Конфиденциальность')} · ${link('consent','Обработка данных')}</div>`);}
function register(){return authShell(`<h1>Создать аккаунт</h1><p class="subheading">Присоединяйтесь к своему клубу SRP.</p><div class="tabs"><button class="active">Регистрация</button>${link('login','Вход','ghost')}</div><form id="register-form">${field('Никнейм','nick','text','','required placeholder="Ваш игровой никнейм"')}${field('Почта или телефон','identity','text','','required placeholder="Вымышленный контакт"')}${field('Пароль','password','password','','required minlength="8" autocomplete="off"')}<label class="field" style="margin-top:18px">Клуб<select name="club">${clubData.map((c,i)=>`<option value="${i}">${esc(c.join(' · '))}</option>`).join('')}</select></label><label class="check-line" style="margin-top:20px"><input type="checkbox" required name="consent">Согласен на обработку персональных данных и ознакомлен с политикой конфиденциальности.</label><div class="auth-errors" role="alert">${esc(state.authError)}</div><button class="primary block" type="submit">Зарегистрироваться</button></form><div class="auth-legal">Форма регистрации требует сверки с SRP. Реальный аккаунт не создаётся.<br>${link('privacy','Конфиденциальность')} · ${link('consent','Обработка данных')}</div>`);}
function reset(){return authShell(`${back('login','Вход')}<h1>Восстановить пароль</h1><p class="subheading">Введите почту или телефон, привязанные к аккаунту.</p><form id="reset-form">${field('Почта или телефон','identity','text','','required placeholder="Вымышленный контакт"')}<button type="submit" class="primary block">Получить код</button></form><div class="auth-legal">В прототипе код не отправляется. Сценарий восстановления требует сверки с SRP.</div>`);}
function verify(){return authShell(`${back(state.verifyPurpose==='reset'?'reset':state.verifyPurpose==='register'?'register':'settings','Назад')}<h1>Подтвердите контакт</h1><p class="subheading">Введите код подтверждения.</p><form id="verify-form">${field('Код','code','text','','required inputmode="numeric" pattern="[0-9]{6}" maxlength="6" placeholder="123456"')}<div class="note">Демонстрационный код: 123456</div><div class="auth-errors" role="alert">${esc(state.authError)}</div><button type="submit" class="primary block">Подтвердить</button></form>${btn('Получить код повторно','resend-code','ghost block small')}`);}
const renderers={home,tournaments,tournament,completed,history,leagues,'city-event':()=>leagueEvent('cities'),'champion-event':()=>leagueEvent('champions'),'rating-event':()=>leagueEvent('rating'),ambassadors:()=>soon('Лига Амбассадоров','Амбассадорская покерная лига. Раздел сохранён со статусом «скоро».'),clubs,club,map,rating,player,profile,achievements,statistics,settings,broadcast,notifications,'push-settings':pushSettings,loyalty:()=>soon('Карта лояльности','Карта лояльности сейчас находится в разработке.'),about,support,updates,install,privacy:()=>legal('privacy'),consent:()=>legal('consent'),welcome,login,register,reset,verify};
Object.assign(renderers,{'player-history':playerHistory,'player-achievements':playerAchievements,'player-statistics':playerStatistics});
screens.splice(screens.findIndex(s=>s.id==='player-statistics')+1,0,{id:'player-result',title:'Результат другого игрока',group:'Клубы и рейтинг',status:'inferred'});
renderers['player-result']=()=>{const p=publicPast[state.publicPastIndex||0];return back('player-history','История игрока')+pageHead(p[0],esc(players[state.player][0]),pill('Завершён'))+`<div class="panel event-page-body">${tabline(['О турнире','Лидерборд','Очки'],state.completedTab||'О турнире','completed-tab')}${state.completedTab==='Очки'?`<div class="info-line"><span>Пулл очков</span><strong>710,41</strong></div><div class="info-line"><span>Средний рейтинг турнира</span><strong>1 032</strong></div><div class="note">Данные очков относятся к исследованному турниру «Баунти ПКО» 06.10.</div>`:state.completedTab==='Лидерборд'?`<table class="data-table"><thead><tr><th>Место</th><th>Игрок</th></tr></thead><tbody><tr><td class="rank">${p[2]}</td><td>${esc(players[state.player][0])}</td></tr></tbody></table>`:`<div class="info-line"><span>Дата</span><strong>${p[1]}.2026</strong></div><div class="info-line"><span>Клуб</span><strong>Milli Club · Казань</strong></div><div class="info-line"><span>Место игрока</span><strong>${p[2]}</strong></div>`}</div>`;};
const navigation=[['home','home','Главная'],['tournaments','calendar','Турниры'],['clubs','pin','Клубы'],['rating','trophy','Рейтинг'],['profile','user','Аккаунт']];
function activeNav(){return ['tournament','completed','history'].includes(state.page)?'tournaments':['club','map'].includes(state.page)?'clubs':state.page.startsWith('player')?'rating':['settings','broadcast','statistics','achievements','push-settings','notifications','loyalty'].includes(state.page)?'profile':state.page;}
function isAuth(){return ['welcome','login','register','reset','verify'].includes(state.page);}
function shell(content){const active=activeNav();return `<div class="client-status"><span class="network-status">● Сеть SRP</span><span class="client-status-tools">Покер не на деньги &nbsp; · &nbsp; RU</span></div><header class="topbar">${link('home',`<img src="${mediaBase}srp-wordmark.svg" alt="СРП"><small>POKER CLUB</small>`,'logo')}<nav class="client-modes" aria-label="Режим приложения">${link('home','ГЛАВНАЯ',state.page==='home'?'active':'')}${link('tournaments','ТУРНИРЫ',active==='tournaments'?'active':'')}${link('leagues','ЛИГИ SRP',state.page.includes('event')||state.page==='leagues'?'active':'')}</nav><button class="club-picker" data-action="club-picker">Мой клуб<strong>${esc(clubData[state.club][0])} · ${esc(clubData[state.club][1])} ${ic('down')}</strong></button><div class="top-actions">${link('notifications',ic('bell'),'icon-button','aria-label="Уведомления"')}${link('profile',`<span>${esc(state.nick)}</span>${avatar()}`,'user-button')}</div></header><nav class="appnav" aria-label="Основная навигация">${navigation.map(([r,i,t])=>link(r,ic(i)+t,r===active?'active':'')).join('')}${link('leagues','Лиги SRP',state.page.includes('event')||state.page==='leagues'?'active':'')}${link('support','Поддержка','nav-right')}</nav><div class="client-body"><main class="main page-${state.page}" id="screen-content">${content}</main>${rail()}</div><footer class="app-footer"><span>SRP · Покер не на деньги</span><div class="footer-links">${link('about','О сети')}${link('privacy','Конфиденциальность')}${link('consent','Обработка данных')}${link('updates','v4.7.0')}</div></footer><nav class="bottomnav" aria-label="Мобильная навигация">${navigation.map(([r,i,t])=>link(r,ic(i)+t,r===active?'active':'')).join('')}</nav>`;}
function specialState(){if(state.viewState==='loading')return pageHead('Загрузка','SRP')+`<div aria-busy="true" aria-label="Экран загружается"><div class="skeleton-line short"></div>${[0,1,2,3].map(()=>'<div class="skeleton-box"><div class="skeleton-line"></div><div class="skeleton-line short"></div></div>').join('')}</div>`;if(state.viewState==='error')return `<div class="panel">${empty('Не удалось загрузить данные','Проверьте подключение и попробуйте ещё раз.',btn('Повторить','normal-state','primary'))}</div>`;return `<div class="panel">${empty('Здесь пока нет данных','Когда появятся события или результаты, они будут доступны на этом экране.',btn('Вернуться к обычному экрану','normal-state','secondary'))}</div>`;}
function render(){if(!renderers[state.page])state.page='home';const s=screens.find(s=>s.id===state.page);document.getElementById('screen-caption').textContent=s.title;document.getElementById('coverage-caption').textContent=({verified:'Функция подтверждена в SRP',unavailable:'Раздел сохранён · содержимое требует сверки',inferred:'Предложенный сценарий · требуется сверка',new:'Новый экран для мобильного приложения'})[s.status];document.getElementById('screen-count').textContent=screens.length;const content=state.viewState==='normal'?renderers[state.page]():specialState();const previousFilm=app.querySelector('.auth-art .srp-video,.video-banner .srp-video');app.innerHTML=isAuth()&&state.viewState==='normal'?content:shell(content);const nextFilm=app.querySelector('.auth-art .srp-video,.video-banner .srp-video');if(previousFilm&&nextFilm&&previousFilm.getAttribute('src')===nextFilm.getAttribute('src')){previousFilm.className=nextFilm.className;nextFilm.replaceWith(previousFilm);}document.title=`${s.title} · SRP · Прототип`;if(state.modal)renderModal();}
function navigate(page,options={}){state.page=page;state.viewState='normal';document.getElementById('state-picker').value='normal';state.search='';state.authError='';if(options.player!==undefined)state.player=options.player;if(options.club!==undefined)state.clubDetail=options.club;if(options.past!==undefined)state.pastIndex=options.past;closeReview();closeModal();render();try{if(location.hash.slice(1)!==page)window.history.replaceState(null,'','#'+page);}catch{}frame.scrollIntoView({behavior:'auto',block:'start'});}
function toast(t){const el=document.getElementById('toast');el.textContent=t;el.classList.add('visible');clearTimeout(state.toastTimer);state.toastTimer=setTimeout(()=>el.classList.remove('visible'),3500);}
function closeModal(){state.modal=null;document.getElementById('modal-root').innerHTML='';if(state.previousFocus?.isConnected)state.previousFocus.focus();}
function modal(title,body,actions=''){state.previousFocus=document.activeElement;state.modal={title,body,actions};renderModal();}
function renderModal(){const m=state.modal;if(!m)return;document.getElementById('modal-root').innerHTML=`<div class="modal-overlay" data-action="overlay-close"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div class="modal-head"><h2 id="modal-title">${m.title}</h2>${btn(ic('close'),'close-modal','icon-button','aria-label="Закрыть"')}</div>${m.body}<div class="modal-actions">${m.actions||btn('Понятно','close-modal','primary')}</div></section></div>`;setTimeout(()=>document.querySelector('.modal button')?.focus(),0);}
function closeReview(){document.getElementById('review-drawer').hidden=true;document.getElementById('review-drawer').innerHTML='';}
const statusNames={verified:'Проверено в SRP',inferred:'Сверить сценарий',unavailable:'Не загрузился в SRP',new:'Новая функция'};
function openCatalog(){let group='';document.getElementById('review-drawer').hidden=false;document.getElementById('review-drawer').innerHTML=`<div class="drawer-overlay" data-action="drawer-overlay"><section class="review-drawer-panel" role="dialog" aria-modal="true" aria-labelledby="catalog-heading"><div class="review-drawer-head"><h2 id="catalog-heading">Все экраны · ${screens.length}</h2>${btn(ic('close'),'close-review','icon-button','aria-label="Закрыть каталог"')}</div><p class="muted" style="font-size:13px;margin-bottom:15px">Каждый экран доступен на компьютере и телефоне. Статус показывает, что удалось проверить на действующем сайте.</p><div class="screen-catalog">${screens.map((s,i)=>{let head='';if(group!==s.group){group=s.group;head=`<div class="catalog-group">${s.group}</div>`;}return head+`<button class="catalog-item" data-route="${s.id}"><span class="catalog-number">${String(i+1).padStart(2,'0')}</span><span><strong>${s.title}</strong><small>${statusNames[s.status]}</small></span></button>`;}).join('')}</div><div class="note">Дополнительно: вкладки, формы подтверждения, отмена записи, успех, ошибки, загрузка и пустые состояния.</div></section></div>`;}
function openJourneys(){document.getElementById('review-drawer').hidden=false;document.getElementById('review-drawer').innerHTML=`<div class="drawer-overlay" data-action="drawer-overlay"><section class="review-drawer-panel" role="dialog" aria-modal="true" aria-labelledby="journey-heading"><div class="review-drawer-head"><h2 id="journey-heading">Сценарии для проверки</h2>${btn(ic('close'),'close-review','icon-button','aria-label="Закрыть"')}</div>${[['welcome','Вход и регистрация','Старт → вход или регистрация → подтверждение → главная.'],['tournaments','Запись на турнир','Найти событие → открыть → записаться → успех → мои турниры → отменить запись.'],['history','Результаты турнира','История → прошедший турнир → лидерборд → очки → статистика.'],['leagues','Путь по лигам','Выбрать лигу → событие или этап → участники → структура → сетка и финал.'],['rating','Найти игрока','Клуб / сеть / неделя → поиск → публичный профиль.'],['achievements','Прогресс достижений','Обычные / редкие → награда → условия → прогресс.'],['settings','Настройки профиля','Фото → никнейм → контакты → код / звонок → пароль → привязки.'],['broadcast','Подготовка трансляции','Карточка игрока → имя и фото → все 11 вопросов анкеты → сохранение.'],['push-settings','Пуш-уведомления','Категории → согласие на приглашения → разрешение устройства → пример пуша.'],['clubs','Выбор клуба','Все / новые / карта → клуб → выбрать → турниры и рейтинг.']].map(([r,t,p])=>`<article class="journey"><h3>${t}</h3><p>${p}</p>${link(r,'Начать сценарий','primary small')}</article>`).join('')}</section></div>`;}
function openEvent(id){state.selected=id;state.detailTab='О турнире';navigate(events[id].route||'tournament');}
function notifyRegistration(e){state.demoNotifications=state.demoNotifications||[];state.demoNotifications.unshift({title:'Вы записаны на турнир',text:`${e.name} · ${e.date} · ${e.time}`,route:'tournament'});}
const actions={
 'trip-plan-save':v=>{const club=Number(v);if(!clubData[club])return;state.tripPlan=state.tripPlan||[];if(!state.tripPlan.some(p=>p.club===club))state.tripPlan.push({club,date:''});save();render();toast('Клуб сохранён в план поездки');},
 'trip-plan-remove':v=>{state.tripPlan=(state.tripPlan||[]).filter(p=>p.club!==Number(v));save();render();toast('Клуб убран из плана');},
 'trip-plan-open':v=>{state.mapClub=Number(v);state.tripCity=clubData[state.mapClub][1];navigate('map');},

'media-slide':v=>{state.mediaSlide=Number(v);render();},
'public-club':v=>{state.publicClub=v;render();},
'public-result':v=>{state.publicPastIndex=Number(v);state.completedTab='О турнире';navigate('player-result');},
'catalog':openCatalog,'journeys':openJourneys,'close-review':closeReview,'close-modal':closeModal,'normal-state':()=>{state.viewState='normal';document.getElementById('state-picker').value='normal';render();},
'reset-demo':()=>modal('Сбросить демонстрацию?','<p>Будут очищены тестовые записи, ответы анкеты и настройки этого прототипа. Рабочий аккаунт SRP не затрагивается.</p>',btn('Отмена','close-modal','secondary')+btn('Сбросить','confirm-reset','danger')),
'confirm-reset':()=>{try{localStorage.removeItem('srp-prototype-v2');}catch{}state.nick=defaults.nick;state.club=0;state.registered=[];state.push={...defaults.push};state.broadcast={};state.avatar=null;state.email='';state.phone='';state.demoNotifications=[];navigate('home');toast('Демонстрация сброшена');},
'select-event':v=>{state.selected=Number(v);state.detailTab='О турнире';if(frame.clientWidth<=720)openEvent(Number(v));else render();},'open-event':v=>openEvent(Number(v)),'event-details':()=>openEvent(state.selected),
'event-filter':v=>{state.filter=v;render();},'clear-filters':()=>{state.filter='Все';state.search='';state.dateFilter='Все даты';render();},'detail-tab':v=>{state.detailTab=v;render();},
'register-event':()=>{const e=events[state.selected];modal('Запись на турнир',`<p><strong style="color:#fff">${e.name}</strong><br>${e.date}.2026 · ${e.time}<br>Milli Club · Казань</p><div class="note">Подтверждение меняет только состояние прототипа.</div>`,btn('Назад','close-modal','secondary')+btn('Подтвердить запись','confirm-registration','primary'));},
'confirm-registration':()=>{const e=events[state.selected];if(!state.registered.includes(e.id))state.registered.push(e.id);notifyRegistration(e);save();closeModal();render();modal('Вы записаны',`<div class="modal-success">${ic('check')}</div><p>${e.name}<br>${e.date}.2026 · ${e.time}<br>Запись доступна в разделе «Мои турниры».</p>`,link('history','Мои турниры','primary')+btn('Продолжить','close-modal','secondary'));},
'cancel-registration':()=>modal('Отменить запись?',`<p>${events[state.selected].name}<br>${events[state.selected].date} · ${events[state.selected].time}</p>`,btn('Оставить запись','close-modal','secondary')+btn('Отменить запись','confirm-cancel','danger')),
'confirm-cancel':()=>{state.registered=state.registered.filter(i=>i!==state.selected);save();closeModal();render();toast('Тестовая запись отменена');},
'completed-tab':v=>{state.completedTab=v;render();},'history-tab':v=>{state.historyTab=v;render();},'more-history':()=>{state.historyLimit=past.length;render();},'league':v=>{state.league=v;state.leagueTab='О турнире';render();},'league-tab':v=>{state.leagueTab=v;render();},'champion-round':v=>{state.round=Number(v);state.leagueTab='О турнире';navigate('champion-event');},
'clubs-tab':v=>{state.clubsTab=v;if(v==='Карта')navigate('map');else navigate('clubs');},'map-club':v=>{state.mapClub=Number(v);state.tripCity=clubData[state.mapClub][1];render();},'map-open-club':()=>{state.clubDetail=state.mapClub;navigate('club');},
'choose-club':v=>{const i=Number(v);modal('Выбрать клуб?',`<p>${esc(clubData[i].join(' · '))}</p><div class="note">Смена клуба в прототипе. Правила смены основного клуба в SRP требуют подтверждения.</div>`,btn('Отмена','close-modal','secondary')+btn('Выбрать','confirm-club','primary',`data-value="${i}"`));},
'confirm-club':v=>{state.club=Number(v);save();closeModal();render();toast('Клуб выбран в прототипе');},
'club-picker':()=>modal('Мой клуб',`<label class="field">Клуб сети SRP<select id="modal-club-select">${clubData.map((c,i)=>`<option value="${i}" ${state.club===i?'selected':''}>${esc(c.join(' · '))}</option>`).join('')}</select></label>`,btn('Отмена','close-modal','secondary')+btn('Выбрать','save-club-picker','primary')),
'save-club-picker':()=>{state.club=Number(document.getElementById('modal-club-select').value);save();closeModal();render();},
'rating-tab':v=>{state.ratingTab=v;render();},'ach-tab':v=>{state.achTab=v;render();},'achievement':v=>{const a=(state.achTab==='Обычные'?ordinary:rare)[Number(v)];modal(a.name,`<div class="empty-icon gold" style="text-align:center;margin-bottom:20px">${ic('trophy')}</div>${a.level?`<div class="eyebrow">Уровень ${a.level}</div>`:''}<p>${a.desc}</p><div class="info-line"><span>Прогресс</span><strong>${Math.min(a.now,a.max)} / ${a.max}</strong></div><div class="progress-track" style="margin-top:20px"><div class="progress-fill" style="width:${Math.min(100,a.now/a.max*100)}%"></div></div>`);},
'location':()=>{state.mapClub=0;state.tripCity='Казань';navigate('map');},
'verify-email':()=>{const v=document.getElementById('contact-email').value;if(!v||!v.includes('@'))return toast('Введите тестовый адрес почты');state.email=v;state.verifyPurpose='email';navigate('verify');},
'verify-phone':()=>{const v=document.getElementById('contact-phone').value;if(v.replace(/\D/g,'').length<10)return toast('Введите тестовый номер телефона');state.phone=v;modal('Подтверждение звонком',`<p>В рабочем SRP контакт подтверждается звонком. Введите проверочный код в демонстрационной форме.</p><label class="field">Код из звонка<input id="call-code" inputmode="numeric" maxlength="4" placeholder="1234"></label><div class="note">Тестовый код: 1234. Реального звонка не будет.</div>`,btn('Отмена','close-modal','secondary')+btn('Подтвердить','confirm-phone','primary'));},
'confirm-phone':()=>{if(document.getElementById('call-code').value!=='1234')return toast('Демонстрационный код: 1234');state.phoneVerified=true;closeModal();render();toast('Телефон подтверждён в прототипе');},
'link-telegram':()=>modal('Привязать Telegram','<p>Рабочее приложение открывает подтверждение привязки в Telegram. Здесь показан конечный результат без обращения к сервису.</p>',btn('Отмена','close-modal','secondary')+btn('Показать успешную привязку','confirm-telegram','primary')),
'link-vk':()=>modal('Привязать VK','<p>Рабочее приложение открывает вход VK. В прототипе можно посмотреть результат успешной привязки.</p>',btn('Отмена','close-modal','secondary')+btn('Показать успешную привязку','confirm-vk','primary')),
'confirm-telegram':()=>{state.telegramLinked=true;closeModal();render();toast('Telegram привязан в демонстрации');},'confirm-vk':()=>{state.vkLinked=true;closeModal();render();toast('VK привязан в демонстрации');},
'logout':()=>modal('Выйти из аккаунта?','<p>Завершить демонстрационный сеанс?</p>',btn('Остаться','close-modal','secondary')+btn('Выйти','confirm-logout','danger')),'confirm-logout':()=>navigate('welcome'),
'telegram-login':()=>modal('Вход через Telegram','<p>В рабочей версии вход подтверждается в приложении Telegram. Здесь можно проверить переход после успешной авторизации.</p>',btn('Отмена','close-modal','secondary')+btn('Показать успешный вход','confirm-login','primary')),'confirm-login':()=>{navigate('home');toast('Добро пожаловать в SRP');},
'resend-code':()=>toast('Демонстрационный код: 123456'),
'sample-push':()=>modal('Предпросмотр пуша',`<div class="panel panel-pad" style="margin-bottom:20px"><div class="eyebrow">SRP · Сейчас</div><h3>Ваш турнир скоро начнётся</h3><p style="margin-top:8px">${events[state.selected].name} · Milli Club · ${events[state.selected].time}</p></div><p>Нажатие на уведомление открывает соответствующий турнир.</p>`,btn('Закрыть','close-modal','secondary')+btn('Открыть турнир','event-details','primary')),
'permission-preview':()=>modal('SRP хочет отправлять уведомления','<p>Уведомления могут включать напоминания, события клуба и результаты. Разрешение можно изменить в настройках устройства.</p><div class="note">Предпросмотр системного запроса. Разрешение устройства не меняется.</div>',btn('Не разрешать','permission-deny','secondary')+btn('Разрешить','permission-allow','primary')),
'permission-allow':()=>{closeModal();toast('Сценарий: разрешение получено');},'permission-deny':()=>{closeModal();toast('Сценарий: приложение работает без пушей');},
'read-notifications':()=>{state.readNotifications=true;render();toast('Уведомления отмечены прочитанными');},
'app-store':()=>modal('Установка на iPhone','<p>После публикации кнопка откроет страницу SRP в App Store. Установка приложения появится после разработки и модерации.</p>'),
'android-store':()=>modal('Установка на Android','<p>После публикации здесь будут ссылки на утверждённые страницы SRP в магазинах приложений.</p>'),
'web-install':()=>navigate('home')
};

const assistantState={open:false,messages:[]};
function assistantCard(route,title,copy='',extra=''){return link(route,`<strong>${esc(title)}</strong><small>${esc(copy)}</small><span>Открыть →</span>`,'assistant-card',extra);}
function assistantSuggestions(){return state.page==='rating'?['Как работает рейтинг?','Где мои результаты?','Как получить достижение?']:state.page==='clubs'?['Найди клуб в Москве','Найди клуб в Казани','Я новичок. С чего начать?']:['Я новичок. С чего начать?','Какие турниры есть в Казани?','Как записаться на турнир?'];}
function assistantAnswer(question){const q=question.toLocaleLowerCase('ru').trim();
const city=clubData.map(c=>c[1]).find(c=>q.includes(c.toLocaleLowerCase('ru').replace(/[ьаыяй]$/,'')));
if(/отмен/.test(q))return `Чтобы отменить запись, открой свой предстоящий турнир и нажми «Отменить запись». В этом прототипе действие демонстрационное.${assistantCard('history','Мои турниры','Открой свою запись')}`;
if(/рейтинг|очк/.test(q))return `В рейтинге можно переключаться между клубом, сетью и неделей и находить игроков. Точную формулу начисления очков нужно сверить с правилами SRP — я не буду придумывать её.${assistantCard('rating','Рейтинг игроков','Клуб · сеть · неделя')}${assistantCard('statistics','Моя статистика','Турниры и результаты')}`;
if(/результат|истори|статист/.test(q))return `История показывает сыгранные турниры, даты и занятые места. Открой турнир, чтобы посмотреть результат подробнее.${assistantCard('history','История турниров','Твои сыгранные турниры')}`;
if(/достиж|наград/.test(q))return `В разделе достижений есть обычные и редкие награды. Открой карточку награды — там показаны её условия и прогресс.${assistantCard('achievements','Достижения','Посмотри условия и прогресс')}`;
if(/нович|перв|начать|не уме/.test(q))return `Начни с клуба в своём городе. Затем выбери подходящий турнир и посмотри его формат, адрес и время. Перед первым посещением уточни у клуба условия участия и правила — на месте тебе объяснят порядок игры.${assistantCard('clubs','Выбрать клуб','Справочник городов и клубов')}${assistantCard('tournaments','Посмотреть турниры','Формат, дата, участники')}`;
if(/запис|регистрац/.test(q))return `Открой турнир → посмотри время, место и формат → нажми «Записаться на турнир» → подтверди запись. Она появится в личном кабинете.${assistantCard('tournaments','Выбрать турнир','Запись в прототипе демонстрационная')}${assistantCard('history','Мои турниры','Проверить свои записи')}`;
if(/турнир|играть|игра|сегодня|завтра/.test(q)){
if(city&&city!=='Казань')return `В макете расписание показано для Milli Club в Казани. Актуальных турниров ${esc(city)} у меня нет. Можно открыть клубы этого города и посмотреть информацию о клубе.${clubData.map((c,i)=>({c,i})).filter(({c})=>c[1]===city).map(({c,i})=>assistantCard('club',c[0],c[1],`data-club="${i}"`)).join('')}`;
let items=events.slice(0,3);if(/завтра/.test(q))items=events.filter(e=>e.date==='08.10').slice(0,3);if(/сегодня/.test(q))items=events.filter(e=>e.date==='07.10').slice(0,3);
return `Вот события из демонстрационного расписания Milli Club · Казань, 7–11 октября 2026. Это данные макета, а не актуальная афиша.${items.map(e=>`<button class="assistant-card" data-action="assistant-event" data-value="${e.id}"><strong>${esc(e.name)}</strong><small>${e.date} · ${e.time} · ${esc(e.type)}</small><span>Открыть турнир →</span></button>`).join('')}`;}
if(/клуб|город|москв|казан/.test(q)||city){if(!city)return `Выбери город в справочнике клубов. Например, спроси «Найди клуб в Москве» или «Найди клуб в Казани».${assistantCard('clubs','Все клубы SRP','Фильтр по городам')}`;return `В справочнике макета есть следующие клубы: ${esc(city)}.${clubData.map((c,i)=>({c,i})).filter(({c})=>c[1]===city).map(({c,i})=>assistantCard('club',c[0],c[1],`data-club="${i}"`)).join('')}`;}
if(/уведом|пуш/.test(q))return `В настройках уведомлений можно выбрать интересующие категории и посмотреть демонстрацию пуша.${assistantCard('push-settings','Настроить уведомления','Приглашения и напоминания')}`;
if(/правил|формат|холдем|баунти|bounty/.test(q))return `Формат, участники и структура находятся в карточке турнира. Общие правила — в разделе о SRP. Если описание неполное, уточни условия у клуба.${assistantCard('about','О SRP и правила','Покер не на деньги')}${assistantCard('tournaments','Форматы турниров','Открой карточку события')}`;
return `Пока я демонстрационный помощник: могу найти клуб, показать турниры макета и объяснить, где находятся запись, рейтинг и результаты. Для этого вопроса лучше обратиться в поддержку.${assistantCard('support','Поддержка SRP','Задать вопрос')}`;
}
function renderAssistant(){const root=document.getElementById('assistant-root');root.className=assistantState.open?'assistant-open':'';root.innerHTML=`<button class="assistant-launcher" data-action="assistant-toggle" aria-expanded="${assistantState.open}" aria-controls="assistant-panel" aria-label="Помощник SRP">${ic('help')}<span>Помощник SRP</span><i>AI</i></button>${assistantState.open?`<button class="assistant-backdrop" data-action="assistant-close" aria-label="Закрыть панель помощника" tabindex="-1"></button><aside class="assistant-panel" id="assistant-panel" role="dialog" aria-label="Помощник SRP"><header class="assistant-head"><div class="assistant-mark">AI</div><div><strong>Помощник SRP</strong><small>Клубы · турниры · твой прогресс</small></div>${btn(ic('close'),'assistant-close','icon-button','aria-label="Закрыть помощника"')}</header><div class="assistant-context">${esc(screens.find(s=>s.id===state.page)?.title||'SRP')} · Демо-режим</div><div class="assistant-messages" id="assistant-messages" role="log" aria-live="polite"><div class="assistant-bubble assistant-bot"><strong>Твой следующий ход?</strong><p>Помогу разобраться в SRP, найти клуб и перейти к нужному турниру. Спроси меня или выбери подсказку.</p></div>${assistantState.messages.map(m=>`<div class="assistant-bubble ${m.role==='user'?'assistant-user':'assistant-bot'}">${m.role==='user'?esc(m.text):m.text}</div>`).join('')}</div><div class="assistant-suggestions">${assistantSuggestions().map(q=>btn(esc(q),'assistant-question','',`data-value="${esc(q)}"`)).join('')}</div><form id="assistant-form" class="assistant-compose"><input name="question" aria-label="Вопрос помощнику" placeholder="Спроси о клубе или турнире…" required maxlength="400" autocomplete="off"><button type="submit" class="primary" aria-label="Отправить вопрос">↑</button></form><small class="assistant-note">Демонстрация сценариев · нейросеть пока не подключена</small></aside>`:''}`;const log=document.getElementById('assistant-messages');if(log)log.scrollTop=log.scrollHeight;}
function assistantReply(q){q=(q||'').trim().slice(0,400);if(!q)return;assistantState.messages.push({role:'user',text:q},{role:'bot',text:assistantAnswer(q)});assistantState.messages=assistantState.messages.slice(-40);renderAssistant();document.querySelector('#assistant-form input')?.focus();}
Object.assign(actions,{'assistant-toggle':()=>{assistantState.open=!assistantState.open;renderAssistant();if(assistantState.open&&state.device!=='mobile'&&window.innerWidth>720)document.querySelector('#assistant-form input')?.focus();},'assistant-close':()=>{assistantState.open=false;renderAssistant();},'assistant-question':assistantReply,'assistant-event':id=>{openEvent(Number(id));assistantState.open=false;renderAssistant();}});
document.addEventListener('keydown',ev=>{if(ev.key==='Escape'&&assistantState.open){assistantState.open=false;renderAssistant();}});
document.addEventListener('click',ev=>{const target=ev.target.closest('[data-action],[data-route],[data-device]');if(!target)return;
if(target.dataset.device){state.device=target.dataset.device;frame.dataset.device=state.device;document.querySelectorAll('[data-device]').forEach(b=>{if(b.tagName==='BUTTON')b.setAttribute('aria-pressed',String(b.dataset.device===state.device));});return;}
if(target.dataset.route){ev.preventDefault();if(target.closest('.assistant-panel')){assistantState.open=false;renderAssistant();}navigate(target.dataset.route,{player:target.dataset.player!==undefined?Number(target.dataset.player):undefined,club:target.dataset.club!==undefined?Number(target.dataset.club):undefined,past:target.dataset.past!==undefined?Number(target.dataset.past):undefined});return;}
const act=target.dataset.action;if(act==='overlay-close'){if(ev.target===target)closeModal();return;}if(act==='drawer-overlay'){if(ev.target===target)closeReview();return;}if(actions[act]){ev.preventDefault();actions[act](target.dataset.value);}
});
document.addEventListener('input',ev=>{const el=ev.target;if(el.dataset.search){state.search=el.value;if(el.dataset.search==='events'){document.getElementById('event-list').innerHTML=eventRows();document.getElementById('event-count').textContent=visibleEvents().length+' событий';}if(el.dataset.search==='players'){document.getElementById('rating-body').innerHTML=ratingRows();}if(el.dataset.search==='clubs'){document.getElementById('club-list').innerHTML=clubCards();document.getElementById('club-count').textContent=`Найдено: ${visibleClubs().length} из ${clubData.length} клубов`;}}
if(el.closest('#broadcast-form')&&['last','first'].includes(el.name)){const form=document.getElementById('broadcast-form');document.getElementById('broadcast-preview-name').textContent=[form.elements.last.value,form.elements.first.value].filter(Boolean).join(' ')||'ИГРОК';}});
document.addEventListener('change',ev=>{const el=ev.target;if(el.dataset.tripDate!==undefined){const club=Number(el.dataset.tripDate);if(!clubData[club]||(el.value&&!tripDateValid(el.value)))return;state.tripPlan=state.tripPlan||[];let item=state.tripPlan.find(p=>p.club===club);if(!item){item={club,date:''};state.tripPlan.push(item);}item.date=el.value;save();render();toast(el.value?'Дата сохранена. Можно добавить напоминание в календарь':'Дата посещения очищена');}if(el.id==='theme-picker'){document.getElementById('prototype').dataset.theme=el.value;try{localStorage.setItem('srp-theme',el.value);}catch{}}if(el.id==='state-picker'){state.viewState=el.value;render();}if(el.dataset.select==='trip-city'){state.tripCity=el.value;state.mapClub=clubData.findIndex(c=>c[1]===el.value);render();}if(el.dataset.select==='club-city'){state.clubCity=el.value;render();}if(el.dataset.select==='date'){state.dateFilter=el.value;render();}if(el.dataset.select==='league-club'){state.club=Number(el.value);save();render();}if(el.dataset.select==='round-stage'){state.roundStage=el.value;render();}if(el.dataset.push){state.push[el.dataset.push]=el.checked;save();toast('Настройки сохранены в прототипе');}if(el.hasAttribute('data-toggle-password'))el.closest('form').querySelectorAll('input[type=password],input[data-was-password]').forEach(i=>{i.dataset.wasPassword='true';i.type=el.checked?'text':'password';});if(['avatar-file','broadcast-photo'].includes(el.id)){const file=el.files?.[0];if(!file)return;if(!file.type.startsWith('image/'))return toast('Выберите изображение');if(file.size>8*1024*1024)return toast('Выберите фото размером до 8 МБ');const reader=new FileReader();reader.onload=()=>{if(el.id==='broadcast-photo'){state.broadcast=Object.fromEntries(new FormData(document.getElementById('broadcast-form')));}if(el.id==='avatar-file')state.avatar=reader.result;else state.broadcastPhoto=reader.result;render();if(state.broadcastPhoto){const preview=document.querySelector('.broadcast-card .avatar');if(preview)preview.innerHTML=`<img alt="Фото для эфира" src="${state.broadcastPhoto}">`;}toast('Фото добавлено только в прототип');};reader.readAsDataURL(file);}});
document.addEventListener('submit',ev=>{const form=ev.target;if(!form.id)return;ev.preventDefault();const data=Object.fromEntries(new FormData(form));
if(form.id==='assistant-form'){assistantReply(data.question);return;}
if(form.id==='login-form'){navigate('home');toast('Тестовый вход выполнен');}
if(form.id==='register-form'){state.pendingUser=data;state.verifyPurpose='register';navigate('verify');}
if(form.id==='reset-form'){state.verifyPurpose='reset';navigate('verify');}
if(form.id==='verify-form'){if(data.code!=='123456'){state.authError='Введите демонстрационный код 123456.';render();return;}if(state.verifyPurpose==='register'){state.nick=state.pendingUser?.nick||defaults.nick;state.club=Number(state.pendingUser?.club||0);save();navigate('home');toast('Демонстрационный аккаунт создан');}else if(state.verifyPurpose==='reset'){modal('Новый пароль',`<form id="new-password-form">${field('Новый пароль','newPassword','password','','required minlength="8" autocomplete="off"')}<button class="primary block" style="margin-top:22px" type="submit">Сохранить пароль</button></form><div class="note">Изменение только в демонстрационном сценарии.</div>`);}else{state.emailVerified=true;navigate('settings');toast('Почта подтверждена в прототипе');}}
if(form.id==='new-password-form'){navigate('login');toast('Пароль обновлён в демонстрационном сценарии');}
if(form.id==='profile-form'){state.nick=data.nick;state.birth=data.birth;save();render();toast('Профиль сохранён в прототипе');}
if(form.id==='password-form'){toast('Пароль обновлён в демонстрационном сценарии');form.reset();}
if(form.id==='broadcast-form'){state.broadcast=data;save();toast('Анкета сохранена в прототипе');}
if(form.id==='support-form'){modal('Обращение принято',`<div class="modal-success">${ic('check')}</div><p>Тема: ${esc(data.topic)}<br>Сообщение сохранено только в демонстрации.</p>`);form.reset();}
});
document.addEventListener('keydown',ev=>{if(ev.key==='Escape'){closeModal();closeReview();}if(ev.key==='Tab'){const container=document.querySelector('.modal')||document.querySelector('.review-drawer-panel');if(!container)return;const els=[...container.querySelectorAll('button,a,input,select,textarea')].filter(el=>!el.disabled);if(!els.length)return;const first=els[0],last=els[els.length-1];if(ev.shiftKey&&document.activeElement===first){ev.preventDefault();last.focus();}else if(!ev.shiftKey&&document.activeElement===last){ev.preventDefault();first.focus();}}});
window.addEventListener('hashchange',()=>{const p=location.hash.slice(1);if(renderers[p])navigate(p);});
try{const themeRoot=document.getElementById('prototype');themeRoot.dataset.theme=themeRoot.dataset.theme||localStorage.getItem('srp-theme')||'dark';}catch{}
document.getElementById('theme-picker').value=document.getElementById('prototype').dataset.theme||'dark';
const initial=location.hash.slice(1);if(renderers[initial])state.page=initial;
render();
renderAssistant();
})();
